### ISSUE TITLE
NewId() is deprecated

### ISSUE THREAD

**Issue by meihaomain** [taojy123/KeymouseGo#10]
大佬  wx.NewId() for _init_ctrls in range(19)其中的wx.NewId()始终报上面那个错误，我是不是那里少安装了。我用wx.Window.NewControlId()就不报上面那个错，但是程序运行不起。还请大佬讲解一二。

**Comment by taojy123** [comment]
按你的描述应该是 wx 的版本太新，请问你的 wxpython 是如何安装的，能否查看下版本号。
我回头更新一下程序，兼容一下

**Comment by taojy123** [comment]
报的错也发出来一下吧

**Comment by meihaomain** [comment]
我找到问题了，是运行错程序了，现在还有一个问题，如何取消窗口一直置前呢，不是最小话哦。还请大佬赐教

**Comment by taojy123** [comment]
`Frame1.py` 文件 71 行
`style=wx.STAY_ON_TOP | wx.DEFAULT_FRAME_STYLE,`
将 `wx.STAY_ON_TOP | ` 删掉就可以取消窗口置顶了

**Comment by meihaomain** [comment]
谢谢   解决了
