### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by littlemengnew** [taojy123/KeymouseGo#102]
有没有后台功能啊，Windows多桌面让他在一个桌面操作也行最好是与应用一起最小化都行；

按键的语句也不太需要一三参数，只有第二个就够用了，可以分分类吗，或者干脆不用一了

**Comment by taojy123** [comment]
是的， KeymouseGo 在 V1 的时候尝试做过后台模拟，坑太多，放弃了。目前原则是尽量精简方便使用。
毕竟要功能全的话，已经有 `按键精灵` 这种业界标杆了 😄
