### ISSUE TITLE
启动关闭快捷键

### ISSUE THREAD

**Issue by DHJ666** [taojy123/KeymouseGo#103]
启动关闭快捷键修改后，不能一直保存，退出软件重新打开会恢复默认

**Comment by Monomux** [comment]
请问你使用的是v3.2.2版本吗？保存快捷键修改等配置的功能是在这个版本之后加入的 #74。
我打包了一份目前最新的程序[KeymouseGo_x86-64.zip](https://github.com/taojy123/KeymouseGo/files/8610092/KeymouseGo_x86-64.zip)，或者你可以自行下载最新的代码打包使用，

**Comment by DHJ666** [comment]
> 请问你使用的是v3.2.2版本吗？保存快捷键修改等配置的功能是在这个版本之后加入的 #74。 我打包了一份目前最新的程序[KeymouseGo_x86-64.zip](https://github.com/taojy123/KeymouseGo/files/8610092/KeymouseGo_x86-64.zip)，或者你可以自行下载最新的代码打包使用，

你好，是最新版3.2.2

**Comment by Monomux** [comment]
> > 请问你使用的是v3.2.2版本吗？保存快捷键修改等配置的功能是在这个版本之后加入的 #74。 我打包了一份目前最新的程序[KeymouseGo_x86-64.zip](https://github.com/taojy123/KeymouseGo/files/8610092/KeymouseGo_x86-64.zip)，或者你可以自行下载最新的代码打包使用，
> 
> 你好，是最新版3.2.2

这个版本其实已经有点老了，在这个release之后又有过几次改动(可以参考下3.2.2发布日期和大部分Pull Requests的时间)，不过作者现在还没有发布新的release.可以先用上面的打包程序，或者clone现在的源码打包下。:wink:

**Comment by taojy123** [comment]
@DHJ666  最新的 4.0 版已发布，可以尝试下载最新版使用。
