### ISSUE TITLE
Win10计划任务运行没有反应，怎么回事？

### ISSUE THREAD

**Issue by githubcow** [taojy123/KeymouseGo#108]
添加任务如图，无法启动程序，不知道问题出在哪里？另外，请问您什么时候会开发一下定时功能？![屏幕截图 2022-05-13 211409](https://user-images.githubusercontent.com/4576272/168291677-e1e01463-3928-4ebc-be0b-05f55412a9cd.png)

**Comment by Monomux** [comment]
已修复命令行形式无法运行的问题 #109

**Comment by ygfly** [comment]
KeymouseGo.exe scripts/0314_1452.txt   弄成 bat文件，然后在计划任务执行。这个不属于程序的问题，最好不要在这里问，而且谷歌完全可以解决这种问题。

**Comment by Monomux** [comment]
> KeymouseGo.exe scripts/0314_1452.txt 弄成 bat文件，然后在计划任务执行。这个不属于程序的问题，最好不要在这里问，而且谷歌完全可以解决这种问题。

你误会了😂，这个issue和你的issue是由于程序本身的问题导致在命令行模式下无法运行，因此计划任务运行没有反应。

**Comment by ygfly** [comment]
我是回答楼主的问题哈。关于4.0无法命令行问题我提了一个issue

**Comment by taojy123** [comment]
目前最新的4.0版本忘记添加命令行调用功能了。
暂时可以先使用老版本 https://github.com/taojy123/KeymouseGo/releases/tag/v3.2.2

@Monomux  已经提交了 PR，我合入和会尽快发布4.1版本

**Comment by taojy123** [comment]
4.1 已发布
https://github.com/taojy123/KeymouseGo/releases/tag/v4.1
可以支持命令行运行
