### ISSUE TITLE
执行脚本大小有限制吗

### ISSUE THREAD

**Issue by meihaomain** [taojy123/KeymouseGo#11]
大佬  我连续两次录屏，时间大概有一分钟左右，下面执行的操作，那个程序就不能动了，要在那里修改呢

**Comment by taojy123** [comment]
录制的脚本贴出来看下

**Comment by meihaomain** [comment]
我找到了在Frame1.py的116行做了限制，但是现在那个exe文件读取的位置在那里呢   请大佬赐教

**Comment by meihaomain** [comment]
我现在想做的是  直接代参数进去，不用下拉框来选择脚本

**Comment by taojy123** [comment]
点击 `启动` 的时候，会调用 `323` 行的 `get_script_path` 方法，获取当前选中的要执行的脚本路径。
如果你想写死要执行的脚本，可以修改 `get_script_path` 里的内容。

另外，你也许可以参考这个 issue: 
https://github.com/taojy123/KeymouseGo/issues/5

**Comment by meihaomain** [comment]
谢谢

**Comment by meihaomain** [comment]
大佬   直接代参数进去，不用下拉框来选择脚本该怎么做呢   例如：python KeymouseGo.py + 脚本
  代码因该在那里改呢

**Comment by taojy123** [comment]
直接 `python KeymouseGo.py 脚本名.txt` 这样就可以了
这个在 Readme 中也有提到的:
https://github.com/taojy123/KeymouseGo#%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E8%BF%90%E8%A1%8C

**Comment by meihaomain** [comment]
不行大佬 .\KeymouseGo.exe /scripts/kn.db  这样运行还是要点击，（其中生成txt后缀我改成了db）
我需要输入命名直接运行那种

**Comment by taojy123** [comment]
```
KeymouseGo.exe  scripts\kn.db
```
这样

**Comment by taojy123** [comment]
之前打包的 exe 有点问题，我重新打包了一下，你可以再这里 https://github.com/taojy123/KeymouseGo/releases/tag/v2.1 重新下载一下。然后再试下我上面发的命令。
如果还是不行，把报错的内容或截图贴一下

**Comment by meihaomain** [comment]
他报这个错failed to execute script keymousergo

**Comment by taojy123** [comment]
去重新下载个 exe 就不会报这个错了

**Comment by meihaomain** [comment]
我用自己生成得exe 就不行

**Comment by meihaomain** [comment]
是不是要添加什么环境变量呀   还有大佬的pynput_demo.py这个有什么用呢

**Comment by meihaomain** [comment]
Traceback (most recent call last):
  File "KeymouseGo.py", line 93, in <module>
    single_run(script_path, run_times)
  File "KeymouseGo.py", line 37, in single_run
    s = file(script_path, 'r').read()
NameError: name 'file' is not defined

**Comment by meihaomain** [comment]
那个37行file 可能要改成open哦

**Comment by taojy123** [comment]
对的，我就是修改了 file 成 open，然后重新打包了。所以让你下载最新的 exe。
你用源码的话 pull 一下就好了。
pynput_demo 里的代码就是 pynput 的简单应用，没什么用。

**Comment by meihaomain** [comment]
大佬               running_text = '%s running..' % script_path.split('/')[-1].split('\\')[-1]  这个如何写成相对路径呢

**Comment by taojy123** [comment]
没理解这里为什么要相对

**Comment by meihaomain** [comment]
大佬               running_text = '%s running..' % script_path.split('/')[-1].split('\\')[-1]  这个如何写成相对路径呢

**Comment by meihaomain** [comment]
代码 frame1 那里210如何写成绝对路径self.scripts = list(filter(lambda s: s.endswith('.txt'), self.scripts))

**Comment by meihaomain** [comment]
我的意思是   我想指定路径读取和保存脚本

**Comment by taojy123** [comment]
现在代码里是从 scripts 目录下读取和保存脚本的。你要修改的话，搜索代码中的 scripts 改成你期望的目录就行

**Comment by meihaomain** [comment]
我这样写  没有创建成功    def get_script_path(self):
        i = self.choice_script.GetSelection()
        if i < 0:
            return ''
        script = self.scripts[i]
        path = os.path.join("E:\mk\create", 'scripts', script)
        print(path)
        return path

**Comment by taojy123** [comment]
这里是“获取”，你需要相应的修改“设定”部分的代码

**Comment by meihaomain** [comment]
大佬   那个我修改不了，他要报错line 456, in OnBtrecordButton
    open(self.new_script_path(), 'w').write(output)  你能帮忙看一下嘛

**Comment by meihaomain** [comment]
#if not os.path.exists('scripts'):
        #    os.mkdir('scripts')
        self.scripts = os.listdir('E:\mk\create')#[::-1]
        self.choice_script.SetItems(self.scripts)
        self.scripts = list(filter(lambda s: s.endswith('.txt'), self.scripts))  在208行那里我修改了，但还是报错呀

**Comment by taojy123** [comment]
报什么错

**Comment by meihaomain** [comment]
原来是度读的位置 不能修改，那大佬   屏幕分辨率你改了那些
