### ISSUE TITLE
你好，无法打开4.0版本，请问啥原因

### ISSUE THREAD

**Issue by 122565123** [taojy123/KeymouseGo#110]
你好，无法打开4.0版本，请问，我的电脑是WIN7系统
![360截图20220514144821049](https://user-images.githubusercontent.com/105536261/168414414-b7b5f1e5-3e45-47a9-b59d-875116eb44d1.jpg)
![360截图20220514143252075](https://user-images.githubusercontent.com/105536261/168414417-ea773c73-562c-404d-80ac-f21bc2e7f559.JPG)

**Comment by 122565123** [comment]
是不是和系统有关系呢 我是WIN7系统

**Comment by Monomux** [comment]
作者采用Python3.10打包的4.0版本，Python3.9及以上已不支持Win7系统，你可以下载安装较低的Python版本(如Python3.8)然后按照[教程](https://github.com/taojy123/KeymouseGo#%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91-%E6%89%93%E5%8C%85-exe-%E6%96%87%E4%BB%B6)打包

**Comment by 122565123** [comment]
谢谢你，我起初不知道原因，鼓捣了好久，甚至重装了电脑，还是没解决，尴尬....

**Comment by 122565123** [comment]
> 作者采用Python3.10打包的4.0版本，Python3.9及已不支持Win7以上的系统，你可以下载安装较低的Python3.8版本（如Python3.8）然后按照[教程](https://github.com/taojy123/KeymouseGo#%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91-%E6%89%93%E5%8C%85-exe-%E6%96%87%E4%BB%B6)打包
谢谢你，我起初不知道原因，鼓捣了好久，甚至重装了电脑，还是没解决，尴尬....

**Comment by taojy123** [comment]
你好，微软官方已经不支持 win7 了，所以我打包的时候没有考虑到 😂

老系统建议使用 3.2.2 版 
https://github.com/taojy123/KeymouseGo/releases/tag/v3.2.2
功能差不多的
