### ISSUE TITLE
4.0版 命令行好像无法执行。

### ISSUE THREAD

**Issue by ygfly** [taojy123/KeymouseGo#111]
换回3.2.2  就又可以执行成功了。

**Comment by Monomux** [comment]
Duplicate of #108，已提交相应PR

**Comment by ygfly** [comment]
等待编译好的Windows程序。4.0大了很多，没有体验到比3.2.2 有什么不同啊。

**Comment by Monomux** [comment]
以前的版本GUI使用wxpython实现，新版用pyside2重写了一下，好处是配置文件保存读取、dpi适配这种以前有过的issue都可以用pyside2的控件实现，坏处是程序大小增加了近2.6倍。

**Comment by taojy123** [comment]
https://github.com/taojy123/KeymouseGo/issues/108 
相同问题
暂时可以先使用老版本 https://github.com/taojy123/KeymouseGo/releases/tag/v3.2.2

**Comment by taojy123** [comment]
4.1 已发布
https://github.com/taojy123/KeymouseGo/releases/tag/v4.1
可以支持命令行执行了
