### ISSUE TITLE
能否显示当前执行的 scripts 行号？

### ISSUE THREAD

**Issue by zhsunlight** [taojy123/KeymouseGo#112]
有些较长的 scripts ，在执行过程由于窗口的反应时间比录制时的反应时间长，导致画面还没有出现就开始点击，无法得到正确的运行结果。想要增加 scripts 中对应行的等待时间，却又不容易定位到该行。如果在执行过程中显示出当前执行的行号，或者在中止执行时，显示当前执行的行号，会让修正 scripts 方便得多。

另外，执行次数能否不要限死最多99次？建议能让用户自行输入需要执行的次数。

**Comment by Monomux** [comment]
1.现在的脚本在执行时会显示当前所执行的脚本索引，如果脚本内没有加行注释的话，索引与对应行数的关系为`行数=索引+1`，不知道这样能不能解决你的问题:thinking:
![img](https://user-images.githubusercontent.com/70839036/168460557-cd2794eb-92aa-4f04-af5b-d3bde7c37b43.png)

2.执行次数限制已修改#109

**Comment by zhsunlight** [comment]
全屏执行过程中并不显示KeymouseGo的画面，等按下F9终止执行后，上图画面下方只显示 finished，无法知道是在哪一行终止执行的。

**Comment by Monomux** [comment]
我在PR里加了一个结束执行时显示当前索引的commit，可以等待下一个版本加入这个功能

**Comment by zhsunlight** [comment]
感谢
