### ISSUE TITLE
可否添加动态加载 python 模块的功能？

### ISSUE THREAD

**Issue by zhsunlight** [taojy123/KeymouseGo#113]
我发现 Issues 中很多提出希望添加一些个性化功能的要求，这些个性化功能很多不太通用，添加后确实会让本项目变得臃肿和难以维护。我建议增加支持插件的功能，最起码支持动态加载 python 模块，以类似现有 scripts 的方式添加，建立一个 codes 子目录，由用户自己选择载哪个模块。用户自己在自定义模块中添加需要的个性化功能。修改一下现有的 scripts 格式，添加一个 pyhton_function 的栏位，在执行到填写了 函数名称 栏位的行，就执行该栏位中填写的函数，直到返回结果，再继续执行下一行。这样，象前面提到的捕捉某个窗口标题，直到窗口标题出现时才执行下一行之类的要求就可以轻易实现，只需要在自定义函数中添加捕捉窗口标题和等待的逻辑就行了。

我最感兴趣的是，这样一来，就可以利用粘贴板来交换数据了，当运行到 scripts 中某一行时，执行自定义的函数，在自定义的函数中修改粘贴板的内容，这样就可以在之后的某行 ctrl + v 粘贴，实现表单填写时允许内容变化的功能。

参考资料：
python动态加载模块、类、函数 https://cloud.tencent.com/developer/article/1568138

**Comment by taojy123** [comment]
很好的想法，KeymouseGo 的初衷是尽量简易。
基于这种拓展机制，可以在保持软件本身极简的情况下，满足使用者的个性化需求。

**Comment by Monomux** [comment]
经过 #115 关于新增功能的调试与讨论，目前最新合入的代码存在无法加载自定义扩展的问题，解决方法为：
修改`UIFunc.py`第4行
```python
from importlib.machinery import SourceFileLoader
```
第91-92行
```python
copyfile(get_assets_path('plugins','Extension.py'),
                     '{0}/plugins/Extension.py'.format(os.getcwd()))
```
第587行
```python
module = SourceFileLoader(class_name, os.path.join(os.getcwd(),'plugins','%s.py' % module_name)).load_module()
```
自定义扩展第一行引入默认扩展改为
```python
from assets.plugins.Extension import Extension
```
此外，对于完善扩展还有以下需求

- [ ] 扩展返回值对程序执行流程的控制
- [ ] 加入日志记录以便调试
- [ ] 提供录制过程的扩展接口

**Comment by zhsunlight** [comment]
> 经过 #115 关于新增功能的调试与讨论，目前最新合入的代码存在无法加载自定义扩展的问题，解决方法为： 修改`UIFunc.py`第4行
> 
> ```python
> from importlib.machinery import SourceFileLoader
> ```
> 
> 第91-92行
> 
> ```python
> copyfile(get_assets_path('plugins','Extension.py'),
>                      '{0}/plugins/Extension.py'.format(os.getcwd()))
> ```
> 
> 第587行
> 
> ```python
> module = SourceFileLoader(class_name, os.path.join(os.getcwd(),'plugins','%s.py' % module_name)).load_module()
> ```
> 
> 自定义扩展第一行引入默认扩展改为
> 
> ```python
> from assets.plugins.Extension import Extension
> ```
> 
> 此外，对于完善扩展还有以下需求
> 
> * [ ]  扩展返回值对程序执行流程的控制
> * [ ]  加入日志记录以便调试
> * [ ]  提供录制过程的扩展接口

@Monomux 看到新的PR了，赞。

我用上一个PR的修改版本运行4天，效果很好。我有将近10万条不规则数据需要通过一个没有提供接口的系统中处理，并将处理结果保存到本地硬盘。处理过程中，需要录入三项数据（账号和密码、待处理数据），然后执行多个操作，通过粘贴板复制三项运行结果，执行完成后保存获得的数据。使用没有插件接口的旧版 KeymouseGo，需要很多技巧才能实现自动化，而且运行过程中不能有一点差错，否则数据会乱，数据弄乱后，又要人工重新设置才能再次执行，所以虽然录了脚本，但并没有提高处理效率，因为需要不断人工干预。而使用有插件接口的新版 KeymouseGo 后，我把输入数据和获取运行结果的任务交给插件完成，通过粘贴板实现数据交换。在插件中判断获得的运行结果是否符合正确结果的特征，如果不符合，就丢弃该次运行结果，并将出错的信息保存在日志文件中。这样处理后，错误率大幅降低，大约每500个循环才出现一个错误，而且出错时，设置了声音报警，效率大大提升。出错时，也并不需要人工干预，直接丢弃该次运行结果就行。之前安排一名同事手工处理，两周一共处理不到3000条数据，按此效率，需要一年多才能处理完全部数据。但现在一台电脑一小时就能处理260多条数据，安排4台电脑同时工作，预计未来两周就能处理完。

目前脚本执行插件接口已经做得很好（比我原先设想还要灵活和强大），这部分暂时没有改进建议。

居于让  KeymouseGo 按用户预期方式运行的需求出发，对于 KeymouseGo 的其它部分提几点建议供参考：
1、脚本录制扩展接口：可以让用户自己实现接口抓取何种数据，然后将用户插件返回的数据记录在 scripts 的扩展栏中。KeymouseGo执行scripts 脚本时，原封不动地将用户数据（甚至将整行 scripts 数据传送给运行接口插件，由用户决定如何使用这些数据。（比如在录制时，用户插件记录了窗口或控件的名称、标题、大小、位置等信息，在 KeymouseGo 执行脚本时，运行接口插件收到这些信息后，可以作出正确的判断，然后控制下一步动作）。

2、将 KeymouseGo 现有的执行脚本的代码细分成各个执行单元，提供指令来操作不同的执行单元。比如说可控制KeymouseGo跳转到某一行scripts脚本的指令；暂停执行当前script文件，去执行另一个script文件的指令：让 KeymouseGo 将当前script 压栈，执行另一个 script，待另一个 script 执行完成后，出栈上一个 script 继续执行；重置当前script，重新开始执行script的指令；设置KeymouseGo各项参数的指令；执行用户插件返回的 scripts 代码片段的指令（也可以简化成发送指定字符串的键盘指令，移动鼠标和点击的指令等）。

具备这些能力后，就可以控制 KeymouseGo 完全按预期方式执行了。比如录制脚本时，录制了主流程，在KeymouseGo执行脚本时，理想状态下完全按主流程执行，但出现分枝流程时（比如网页出现了 403 Forbidden），可以通过临时执行一次分枝流程的script脚本（比如清除浏览器 cookies）让系统恢复到正常状态。

**Comment by Monomux** [comment]
> 1、脚本录制扩展接口：可以让用户自己实现接口抓取何种数据，然后将用户插件返回的数据记录在 scripts 的扩展栏中。KeymouseGo执行scripts 脚本时，原封不动地将用户数据（甚至将整行 scripts 数据传送给运行接口插件，由用户决定如何使用这些数据。（比如在录制时，用户插件记录了窗口或控件的名称、标题、大小、位置等信息，在 KeymouseGo 执行脚本时，运行接口插件收到这些信息后，可以作出正确的判断，然后控制下一步动作）。

目前在新的PR中录制接口的处理方法是为封装的事件提供一个扩展属性(`addon`)，录制完一个事件时扩展属性默认为`None`，调用录制接口时，用户可以通过修改`event.addon`加入自己想要记录的内容(可以是任何数据类型，但需要实现`__str__`方法以便保存)，甚至可以修改录制的内容，同时可以通过接口返回值决定该次录制的内容是否要保存。执行时每行脚本的内容被封装成一个事件`event`，扩展属性也会被加载`event.addon`，对于默认扩展来说没有影响。

> 2、将 KeymouseGo 现有的执行脚本的代码细分成各个执行单元，提供指令来操作不同的执行单元。比如说可控制KeymouseGo跳转到某一行scripts脚本的指令；暂停执行当前script文件，去执行另一个script文件的指令：让 KeymouseGo 将当前script 压栈，执行另一个 script，待另一个 script 执行完成后，出栈上一个 script 继续执行；重置当前script，重新开始执行script的指令；设置KeymouseGo各项参数的指令；执行用户插件返回的 scripts 代码片段的指令（也可以简化成发送指定字符串的键盘指令，移动鼠标和点击的指令等）。

目前只实现了跳转到某一行的操作，因为更加复杂的流程控制实现起来有点麻烦。

如果需要实现更复杂的自定义功能，我有个纯粹的想法：提供更高一级的扩展支持，让用户可以直接修改脚本的执行逻辑，从而达到定制流程控制的目的。现在的单次脚本执行在`RunscriptClass.run_script_once`函数中，可以写个`RunscriptClass`的子类实现相关逻辑。

**Comment by zhsunlight** [comment]
> 目前在新的PR中录制接口的处理方法是为封装的事件提供一个扩展属性(`addon`)，录制完一个事件时扩展属性默认为`None`，调用录制接口时，用户可以通过修改`event.addon`加入自己想要记录的内容(可以是任何数据类型，但需要实现`__str__`方法以便保存)，甚至可以修改录制的内容，同时可以通过接口返回值决定该次录制的内容是否要保存。执行时每行脚本的内容被封装成一个事件`event`，扩展属性也会被加载`event.addon`，对于默认扩展来说没有影响。

这个方案应该和我说的具有相同的效果。我测试一下新PR。



> 如果需要实现更复杂的自定义功能，我有个纯粹的想法：提供更高一级的扩展支持，让用户可以直接修改脚本的执行逻辑，从而达到定制流程控制的目的。现在的单次脚本执行在`RunscriptClass.run_script_once`函数中，可以写个`RunscriptClass`的子类实现相关逻辑。

你这个方案也挺好，由用户自己实现特定用途的控制逻辑。我提的方案只是想降低用户编写脚本的难度，将一些通用、常用的控制逻辑在核心层进行标准化实现，供用户插件调用。

**Comment by zhsunlight** [comment]
> 这个可以通过修改传入的event内容修改当前行的执行内容，如果要修改其它行的内容，考虑在扩展初始化时传入整个脚本的事件集合。

我指的是KeymouseGo画面上那些参数，可以在插件代码中修改并立即生效。（主要是想修改执行次数，其它参数在代码中修改的意义不大。）



> 此外还想到了终止本次执行和终止所有执行。

这个是很有必要的。我前几天录制了一个脚本，将执行次数设置为2000次，由于我的执行插件会将不正确的运行结果丢弃，所以每次运行大约能得到1700个正确结果（当然可以设置为大一点的执行次数，比如2400次而得到一个接近2000的正确结果数）。我就想，能不能将执行次数设置为0（无限执行次数），达到2000个正确结果后在插件代码中强制停止执行。结果没有找到实现方法，只好作罢。

目前提供的扩展插件事件能满足大部分情况了。如果有可能，请加上一个全部循环执行完成后的事件，主要用于记录全部循环的执行情况，目前只能在每次循环中记录，需要反复读写文件。

最新PR版本已经测试完成，录制插件及执行插件接口都能正常工作，日志输出功能也完美，对于绝大部分应用场景，通过编写插件已经能完美实现。现在就差改进控制部分的功能了，完善控制部分的功能后，几乎所有应用场景都能全方位满足。

其实现在也可以在执行插件中实现额外的延时效果，再加目前版本跳功能，也能在一定程度上控制KeymouseGo了。比如我今天录制的一个脚本，在录制时，浏览器一秒钟完成打开网页。而在实际执行时，虽然大部分时间是在一秒内打开网页，但偶尔会出现不能在一秒内打开的情况，此时能看到鼠标在空白屏幕上点击，后续执行结果错误。后来我在执行插件中检测窗口标题，发现标题不正确时，就延时0.5秒（ time.sleep(0.5)），之后极少出现在空白屏幕点击的情况。

**Comment by zhsunlight** [comment]
@taojy123 @Monomux PR[119](https://github.com/taojy123/KeymouseGo/pull/119) 已超额实现本工单所提需求，具备支持插件运行所需的一切条件，具有里程碑意义，建议PR119版本号为5.0

我随后将分享一些使用插件的经验。

**Comment by zhsunlight** [comment]
示例1：辅助脚本录制
功能：录制脚本时，规范点击、按键的延时；记录点击区域的图像，方便确定该脚本行的作用。
参考脚本：在插件的 onrecord 中添加如下代码：
![image](https://user-images.githubusercontent.com/56898908/172298026-5f1b64ea-90ee-4648-b727-3afcb8ae01bb.png)

录制脚本后，会在 img 子目录下存放录制时捕捉到的图像：
![image](https://user-images.githubusercontent.com/56898908/172298149-afc40fa5-e819-4af4-920d-bb130dad8973.png)

录制到的脚本：
![image](https://user-images.githubusercontent.com/56898908/172298285-47d9f650-d5a0-45e6-bc9e-bf8b133ef0b3.png)

**Comment by zhsunlight** [comment]
示例2：监控脚本执行结果
功能：在脚本执行过程中，有些步骤故障率极高，比如下载文件，由于受文件大小、网络速度、服务器负载波动等因素的影响，下载时间很难预估，通常的做法是设置一个远大于所需要的下载时间，确保下载成功。但这样一来，原本1分钟能执行完一个循环的脚本，就可能要设置成5分钟执行完，脚本执行效率大幅下降。用插件监控执行情况，可以做到不浪费1秒的等待时间，一下载完成，立即执行下一行脚本。本示例以示例1录制的脚本为例，说明如何监控脚本执行结果。

直接上代码，在插件的 onrunbefore 添加如下代码：
![image](https://user-images.githubusercontent.com/56898908/172337840-45ff2c47-b8c7-437e-b4b6-7d90807bde1a.png)
当脚本执行到示例1脚本中最后一个红框处的脚本行时（即有4-1654576713835.png文件名的行，文件是在录制脚本时，由于点击 打开文件而捕捉到，具体看示例1），搜索屏幕截图中是否存在4-1654576713835.png目标图片【由自定义函数 location=find_image_wait(image, 10)负责搜索，其中参值10表示最多连续搜索10秒钟，一旦搜索到，立即返回，如果没有在10秒内搜索到，也返回一个空的 location】。如果搜索到目标图片，说明下载已完成，返回 location 表示目标图片所在屏幕位置；如果不存在，说明下载还没有完成，此时跳回脚本中每二个红框处的脚本行，重新开始下载。（这里的故障处理逻辑只是示例，实际的脚本中，还可以通过运行分支处理流程脚本等多种方式来处理故障。）

**Comment by zhsunlight** [comment]
@Monomux 使用新版本已经有一段时间，之前无法用 KeymouseGo 完成的重复工作，现在都能用了，一些复杂的工作流程，通过编写插件，可完美地实现自动化。有插件加持的脚本，适应性更广泛，解决问题的能力更强大。

制作脚本时，做一个父流程脚本和若干子流程脚本即可，在插件中根据条件判断使用哪个子流程，与常规编程无异。举一个父流程例子：
![image](https://user-images.githubusercontent.com/56898908/173464394-33144b52-8246-41a6-b13a-75c79f9d716d.png)
在这个例子中，子流程包括打开Chrome浏览器子流程，安装Chrome扩展子流程等等。举一个安装Chrome扩展子流程脚本例子：
![image](https://user-images.githubusercontent.com/56898908/173464716-a535484a-06ef-459c-87de-fc4a9f7a3b7b.png)
相信以后类似这样使用KeymouseGo的方式会变得很流行，原因是这种方式可解决的问题更广泛，通用性和适应性更强。

但随之而来的一个问题是：在插件代码中会大量使用 time.sleep()函数实现延时、等待。time.sleep()这个函数是以阻塞方式工作，即使按下停止脚本执行的快捷键，也得等当前设置的等待时间执行完成。所以在调试脚本和执行脚本时，无法立即停止脚本执行，相当多时间消耗在等待脚本停止执行上面。

可否提供一个非阻塞式的延时函数，供插件调用？

**Comment by ZutJoe** [comment]
我们这个程序也没有啥额外的线程吧， 目前有的就是调用提示音开了一个额外的线程

**Comment by zhsunlight** [comment]
> 我们这个程序也没有啥额外的线程吧， 目前有的就是调用提示音开了一个额外的线程

在插件中使用了 time.sleep()时，尤其是在 while 之类的循环中使用 time.sleep()，如下图：
![image](https://user-images.githubusercontent.com/56898908/173468310-c219d079-c904-48de-a0b7-1e67eeadcee4.png)

一旦进入 While循环，即使已经按下停止键，也得等到该循环执行到 timeout 的时间。

**Comment by Monomux** [comment]
> 一旦进入 While循环，即使已经按下停止键，也得等到该循环执行到 timeout 的时间。 由于上图中，time.sleep()的时间只有0.1秒，这样看来，说应该是进入 while循环后，没有收到和响应停止执行通知导致的。 另外，如果 time.sleep()的延时时间比较长，是否也有相同问题？比如 time.sleep(180）

和 #124 中关于延时的问题相同，因为time.sleep是阻塞式的，目前可以参考event.execute部分的延时实现，采用设置线程事件的标志和非阻塞式的event.wait解决。
```python
if thd:
    thd.event.clear()
    thd.event.wait(timeout=self.delay / 1000.0)
    thd.event.set()
else:
    time.sleep(self.delay / 1000.0)
```

问题是命令行形式运行时并不会创建thread对象，这个方法目前不适用命令行模式，之后还需要修改一下`RunScriptClass`
