### ISSUE TITLE
UI缩放建议

### ISSUE THREAD

**Issue by cyoukon** [taojy123/KeymouseGo#114]
你好，界面能否根据显示器的缩放比例自定调整呢。
27寸4k屏，在150%缩放比例下，字太小了
![image](https://user-images.githubusercontent.com/48378332/169441224-29f50e12-2efd-425d-83b7-f3574e379091.png)

**Comment by Monomux** [comment]
这个可以开启Qt的DPI适配，在`UIFunc.py`的类定义前加上
```
os.environ['QT_ENABLE_HIGHDPI_SCALING'] = "1"
QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
```

**Comment by cyoukon** [comment]
> 这个可以开启Qt的DPI适配，在`UIFunc.py`的类定义前加上
> 
> ```
> os.environ['QT_ENABLE_HIGHDPI_SCALING'] = "1"
> QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
> ```

谢谢，现在没问题了

**Comment by ZutJoe** [comment]
看见一个类似的，高分辨，dpi

https://stackoverflow.com/questions/43904594/pyqt-adjusting-for-different-screen-resolution
