### ISSUE TITLE
python写的话，是不是可以打个macOS包

### ISSUE THREAD

**Issue by xavierchen2021** [taojy123/KeymouseGo#117]

**Comment by Monomux** [comment]
现在的监听和模拟键鼠操作的功能都是通过windows api或是只能在windows上使用的库实现的，因此只支持windows。2.x版支持Mac

**Comment by taojy123** [comment]
是的，2.x版本使用 pyuput 监听鼠标键盘，但坑比较多，所以后来放弃了。
有兴趣在 mac 上用的话，可以下载老版本试下 https://github.com/taojy123/KeymouseGo/releases/tag/v2.2

**Comment by xavierchen2021** [comment]
谢谢，我试试

2022年6月1日 上午11:31，taojy123 ***@***.******@***.***>> 写道：



是的，2.x版本使用 pyuput 监听鼠标键盘，但坑比较多，所以后来放弃了。
有兴趣在 mac 上用的话，可以下载老版本试下 https://github.com/taojy123/KeymouseGo/releases/tag/v2.2
