### ISSUE TITLE
录制插件会把中文记录为乱码

### ISSUE THREAD

**Issue by zhsunlight** [taojy123/KeymouseGo#118]
录制有中文时，出现如下图所示的乱码文件，而且在执行脚本时，也只能部分正确解码中文，仍有部分中文未能正确解码。
![image](https://user-images.githubusercontent.com/56898908/171632252-d0b35a59-42bd-458b-9791-ab2725c05a39.png)
![image](https://user-images.githubusercontent.com/56898908/171633137-49f0f3e9-9dbd-4598-9a8f-4f7551525309.png)

希望能在 scripts 文件中显示出正常的中文，这样后续处理才容易引用。
参考资料：
1、python3 读写中文文件 https://blog.csdn.net/whatday/article/details/107378726
2、解决 python 输出/写中文到 txt 打开看是乱码的问题 https://blog.csdn.net/beguile/article/details/103566583

**Comment by zhsunlight** [comment]
另外，看到保存录制脚本文件的代码中有打开和写入文件的代码，但没有关闭文件的代码，是否疏忽没写？（文件能正常保存的，有可能是我不了解这种写法。）
![image](https://user-images.githubusercontent.com/56898908/171637361-a42c2473-c531-4815-89f5-8de6eb886690.png)

**Comment by Monomux** [comment]
> 另外，看到保存录制脚本文件的代码中有打开和写入文件的代码，但没有关闭文件的代码，是否疏忽没写？

open产生了匿名的对象，由于没有引用，gc会处理这个对象，相当于执行了close。
