### ISSUE TITLE
建议增加执行次数的响应时间，

### ISSUE THREAD

**Issue by gbaoye** [taojy123/KeymouseGo#12]
一秒钟真的太长了

**Comment by taojy123** [comment]
没理解是什么意思，具体说一下哈

**Comment by gbaoye** [comment]
> 没理解是什么意思，具体说一下哈

就添加执行次数之间的衔接时间
我玩魔兽世界 不断的重复一个按键，但是重复第二次执行次数的时候，明显缓慢

**Comment by taojy123** [comment]
哦哦  了解了。下个版本加一下这个 feature

**Comment by taojy123** [comment]
@gbaoye 更新了一个版本，通过设置脚本中的第一个参数，可以改变每一轮执行之间的时间间隔。
具体可以参见 v2.2 的 release 说明
https://github.com/taojy123/KeymouseGo/releases/tag/v2.2
