### ISSUE TITLE
录制完新脚本后，脚本选择列表不显示最新录制的脚本文件名

### ISSUE THREAD

**Issue by zhsunlight** [taojy123/KeymouseGo#120]
录制完新脚本后，KeymouseGo界面脚本选择列表选中的是刚打开程序时的脚本名称，即使刚打开时选择了其它的脚本，录制完成后也是变成刚打开时默认选中的脚本名称，但按快捷键执行时，执行的却是最新录制的脚本。此问题从4.0版本开始就存在（更早版本我没有用过，不清楚是否存在此问题。）

如图，我打开KeymouseGo后，选择了一个脚本：
![image](https://user-images.githubusercontent.com/56898908/171989885-68172f16-04a9-4610-8b6f-8b8beaf7be21.png)

然后开始录制新脚本。录制完成后，显示的是下图的脚本（zing_6_template.txt是刚打开KeymouseGo时默认选中的脚本），此时按F4执行的是刚刚录制的、还没有改名的新脚本。
![image](https://user-images.githubusercontent.com/56898908/171989709-062a5d66-8ddb-4544-be21-9712c27929a9.png)

**Comment by Monomux** [comment]
UI逻辑有点小问题😕，在新的PR里顺带修复了。

**Comment by Johnnyue** [comment]
用的4.1版本，录制的脚本默认使用日期时间命名且不可修改？但是例如12:00分录制了一个脚本，12:05又录制了一个新的脚本，直接按快捷键可以运行新的脚本，但是从列表里面选12:05的脚本运行的话要不然就是打不开，要不然就是之前的脚本。脚本数量多的话情况更乱。希望大佬修复一下，最好是能加上自己命名脚本的功能。

**Comment by zhsunlight** [comment]
> 用的4.1版本，录制的脚本默认使用日期时间命名且不可修改？但是例如12:00分录制了一个脚本，12:05又录制了一个新的脚本，直接按快捷键可以运行新的脚本，但是从列表里面选12:05的脚本运行的话要不然就是打不开，要不然就是之前的脚本。脚本数量多的话情况更乱。希望大佬修复一下，最好是能加上自己命名脚本的功能。
这个不显示最新录制文件名问题已经在[PR#119](https://github.com/taojy123/KeymouseGo/pull/119)中修复。修改脚本文件名的功能在下一版本中将会提供（@[ZutJoe](https://github.com/Monomux/KeymouseGo/issues?q=is%3Apr+is%3Aopen+author%3AZutJoe)正等待合入）。
