### ISSUE TITLE
不支持游戏操作录制

### ISSUE THREAD

**Issue by AUndead** [taojy123/KeymouseGo#121]
在打开原神后弃用录制发现鼠标移动的(移动角色视角)的操作无法录制

**Comment by Monomux** [comment]
游戏里一般有反外挂机制，现在的录制和模拟操作都是系统层面的。像原神这种基于Unity开发的游戏，一种反外挂的方式是用DirectX的DirectInput捕捉键鼠输入，消息是在驱动层面完成的从而绕过了系统层，本软件就无法捕捉键鼠操作。（不确定游戏是不是真的用了这种方法，但如果消息是从系统层传入的程序应该可以捕捉到）

**Comment by AUndead** [comment]
应该是这样的,打开地图后能正常捕获,关掉地图后就不支持了

**Comment by taojy123** [comment]
嗯，游戏辅助是门大学问，咱这就不对游戏做特殊支持了
