### ISSUE TITLE
希望能增加一个随机参数的功能

### ISSUE THREAD

**Issue by Mishasama** [taojy123/KeymouseGo#122]
应用起来大概像这样的：

1. 每次执行该行时，在其一个指定的时间段内随机设置等待时间，然后再执行。
2. 每次执行该行时，对定义好的鼠标目标位置根据一个定义好的像素偏移范围内进行随机偏移并执行。

多少增加点变数，模拟真人操作。
至于原因或者应用场景，有很多种，你懂的。

**Comment by Monomux** [comment]
现在正在实现自定义插件功能，当新版本发布后这个功能可以通过编写相应插件实现。

**Comment by Monomux** [comment]
每行脚本会解析成一个ScriptEvent对象，在插件中可以通过改变`event.delay`实现随机等待时间，改变`event.action`实现随机偏移范围。

示例:

1. 限制1，2行执行时间在200ms~240ms
2. 限制1，2行鼠标范围在(420，200)~(440，220)

```python
from assets.plugins.Extension import *
from loguru import logger
import random
from UIFunc import SW, SH

logger.info('import Real')


class MyExtension(Extension):
    def __init__(self, runtimes, speed, thd=None, swap=None):
        super().__init__(runtimes, speed, thd, swap)
        self.lowertime, self.highertime = 200, 240
        # 绝对坐标
        self.posx = [420, 440]  # xlower, xhigher
        self.posy = [200, 220]  # ylower, yhigher
        # 相对坐标
        self.rposx = [i / SW for i in self.posx]
        self.rposy = [i / SH for i in self.posy]
        self.use_relative_pos = True
        # 应用随机变化的脚本行
        self.indexstochange = [0, 1]

    def onrunbefore(self, event, currentindex):
        if currentindex in self.indexstochange:
            event.delay = random.randint(self.lowertime, self.highertime)
            if event.event_type == 'EM':
                if self.use_relative_pos:
                    posx = random.uniform(self.rposx[0], self.rposx[1])
                    posy = random.uniform(self.rposy[0], self.rposy[1])
                    event.action = [('{}%'.format(i)) for i in [posx, posy]]
                else:
                    posx = random.randint(self.posx[0], self.posx[1])
                    posy = random.randint(self.posy[0], self.posy[1])
                    event.action = [posx, posy]
        return True

```

**Comment by Mishasama** [comment]
> 每行脚本会解析成一个ScriptEvent对象，在插件中可以通过改变`event.delay`实现随机等待时间，改变`event.action`实现随机偏移范围。

可否考虑设计成不在插件里写脚本？改为插件功能通过读取脚本的对应变量来实现？
不然脚本编辑起来很不直观，嵌套修改很难debug的。

**Comment by Monomux** [comment]
> 可否考虑设计成不在插件里写脚本？改为插件功能通过读取脚本的对应变量来实现？

不太理解这句话的意思，脚本本身还是保存在录制后产生的文件中的，执行时程序会先解析脚本内容，将其转换为事件对象列表，再逐一执行。现在插件的各个接口在每个脚本执行前后调用，可以通过修改event的相应内容对执行效果产生影响，对脚本文件本身是没有改动的。

同样的，因为每行脚本内容都被解析为一个事件对象，一行脚本中不同部分的内容都可以通过调用对象的不同属性查看。

调试的话目前可以结合日志模块辅助。

**Comment by Mishasama** [comment]
> > 可否考虑设计成不在插件里写脚本？改为插件功能通过读取脚本的对应变量来实现？
> 
> 不太理解这句话的意思，脚本本身还是保存在录制后产生的文件中的，执行时程序会先解析脚本内容，将其转换为事件对象列表，再逐一执行。现在插件的各个接口在每个脚本执行前后调用，可以通过修改event的相应内容对执行效果产生影响，对脚本文件本身是没有改动的。
> 
> 同样的，因为每行脚本内容都被解析为一个事件对象，一行脚本中不同部分的内容都可以通过调用对象的不同属性查看。
> 
> 调试的话目前可以结合日志模块辅助。

那我举个例子，不知道目前是不是这样的：
1. 首先，录制的时候，出来的脚本是不带任何插件内容的。
2. 如果我要用随机等待时间，则需要去插件那，针对单一特定脚本，生成一个脚本，分别去定义每一行的时间。而这个过程中，原来的脚本不需要做任何的改动。
3. 结果就是，生成了两份脚本，主程序需要把这两份脚本都读取一遍，然后结合成一个事件列表，再逐一执行。

**Comment by Monomux** [comment]
>     2. 如果我要用随机等待时间，则需要去插件那，针对单一特定脚本，生成一个脚本，分别去定义每一行的时间。而这个过程中，原来的脚本不需要做任何的改动。
> 
>     3. 结果就是，生成了两份脚本，主程序需要把这两份脚本都读取一遍，然后结合成一个事件列表，再逐一执行。

按效果来看是在运行时根据插件修改原有的脚本，然后执行修改后脚本的内容。

我上面的示例写的不好，不手动定义每行的具体参数也是可以实现随机参数的功能的。

示例:

1.  所有行执行时间偏移5ms
2.  限制1，2行鼠标范围在x, y轴均偏移20px

```python
from assets.plugins.Extension import *
from loguru import logger
import random, re, copy
from UIFunc import SW, SH


class MyExtension(Extension):
    def __init__(self, runtimes, speed, thd=None, swap=None):
        super().__init__(runtimes, speed, thd, swap)
        # 时间偏移量
        self.biastime = 5
        # 绝对坐标偏移量
        self.biasposx, self.biasposy = 20, 20
        # 应用随机变化的脚本行
        self.indexstochange = [0, 1]

    def onrunbefore(self, event, currentindex):
        cevent = copy.copy(event)
        cevent.delay = event.delay + random.randint(-self.biastime, self.biastime)
        cevent.delay = max(cevent.delay, 0)        
        if currentindex in self.indexstochange:
            if event.event_type == 'EM':
                posx, posy = event.action
                # 相对坐标转绝对坐标
                if not isinstance(posx, int) and not isinstance(posy, int):
                    posx = float(re.match('([0-1].[0-9]+)%', posx).group(1)) * SW
                    posy = float(re.match('([0-1].[0-9]+)%', posy).group(1)) * SH
                posx = int(posx) + random.randint(-self.biasposx, self.biasposx)
                posy = int(posy) + random.randint(-self.biasposy, self.biasposy)
                posx = min(max(posx, 0), SW)
                posy = min(max(posy, 0), SH)
                cevent.action = [posx, posy]
        cevent.execute(self.thd)
        logger.debug(cevent)
        # 执行修改过的事件而不是原有事件
        return False
```

**Comment by Mishasama** [comment]
> 按效果来看是在运行时根据插件修改原有的脚本，然后执行修改后脚本的内容。
> 
> 插件本质上就是提供了一些接口，在执行每行脚本前后、每轮执行前后运行一些自定义的内容。上面的示例就是在执行每行脚本前先修改一下实际执行的参数。我上面的示例写的不好，不手动定义每行的具体参数也是可以实现随机参数的功能的。
> 
> 示例:
> 
> 1. 所有行执行时间随机偏离一定范围，最大偏离5ms
> 2. 限制1，2行鼠标范围在x, y轴均随机偏离一定值，最大偏离20px
> 

这里提出几个问题，不知道目前是不是这样：

1. 首先，这样做是否会导致主程序的脚本和插件的脚本分离，形成两个文件？
每次需要执行原定的操作时都必须手动匹配两个脚本来协同工作才能完成预期的目标？
3. 脚本编辑时的便捷性/可读性是否非常差？
就目前主程序所使用的脚本来说，普通用户还是勉强能透过阅读说明文档来快速理解并进行所需的修改。但一旦引入了这个插件，看起来就对非代码技术人员绝缘了。主代码和变量直接混在一起完全是“不可操作”的。（虽然说我能通过注释大致明白要怎么改，但还是看着有点头大）
而且就算是会编辑代码的专业人员，如果需要两个文件并排，并且要左顾右盼的在脑内模拟合并后的结果来对照修改，想必那体验是绝对的不好的。
5. 现在的“插件”更像是“mod”而不是“plugin”？
通过“外部”脚本来改变原来脚本的内容，进而影响具体的执行内容，这操作是不是有点不太自然“原生”？
不是应该由主程序提供接口，通过引入插件来扩充主程序所能提供的功能吗？
比如：就以当前的例子，原程序在脚本中只能识别像“20”这样的整数纯数字作为等待时间。而加上扩展后，则变成能够识别“10-30”这种格式作为“10~30范围内随机取值”来作为等待时间。
而现在给我的感觉就像外挂一样对主程序进行hacking，在主程序的视角里基本上对插件所进行的操作是毫无感知的。我不知道这样做是好还是坏，还是说只是我的知识比较落后，习惯了传统的交互逻辑。


我不是专业的编程人员，这些问题在专业人士面前可能看起来很蠢，还望海涵。我没有恶意，如造成了困扰，这里先抱歉了😅

**Comment by Monomux** [comment]
### 首先，这样做是否会导致主程序的脚本和插件的脚本分离，形成两个文件？ 每次需要执行原定的操作时都必须手动匹配两个脚本来协同工作才能完成预期的目标？

先说明一下：插件中记录的是对原脚本的修改操作、对脚本执行流程的修改操作核其它自定义功能的实现。我的想法是在运行时，原脚本已解析为事件列表，**插件提供的操作都是对事件列表内容的修改，对事件列表执行流程的修改等**，因此不存在`插件脚本`这一说，如果我的理解与你相悖，可以请你说明一下对`插件脚本`的理解。

>  不是应该由主程序提供接口，通过引入插件来扩充主程序所能提供的功能吗？

怎么说呢，画张加入插件功能前程序执行时的流程图：
![Workflow old drawio](https://user-images.githubusercontent.com/70839036/174012600-85de1926-0a9e-44b4-ac9a-18f63f4cc09a.png)

加入插件功能后的：
![Workflow drawio](https://user-images.githubusercontent.com/70839036/174012616-7326de3d-65ae-4482-a838-a282a4e00185.png)

变化在于可以通过接口返回值和抛出异常修改执行流程，同时在接口内也可以执行自定义的内容。默认的扩展对象接口内什么都不会做，程序执行效果就相当于第一张图。

在引入插件前，程序所能做的功能是`录制键鼠操作`以及`执行已录制的键鼠操作`，录制的脚本一旦确定，在运行时不会改变涉及的操作内容(如改变执行参数，做额外操作)。加入自己设定的扩展后所主程序所能做的内容不是增加了吗？

### 脚本编辑时的便捷性/可读性是否非常差？
> 主代码和变量直接混在一起完全是“不可操作”的。而且就算是会编辑代码的专业人员，如果需要两个文件并排，并且要左顾右盼的在脑内模拟合并后的结果来对照修改，想必那体验是绝对的不好的。

`主代码`和`变量`混在了一起？不能理解。以后给出的示例为例，要实现参数变化，至少需要给出一个参数变化的范围吧？不定义成变量，在调用相应函数时也得输个值进去吧？然后，在每行脚本执行前，先确认一下该行操作的类型，随机改变一下执行的参数，手动执行改过的事件，返回False告知主程序跳过原事件的执行，就实现了参数的变化。去掉示例二中关于坐标的改变你会发现这个功能可以适用于其它脚本，而且不需要知道脚本内容也可以编写。

至于`应用随机变化的脚本行`是看这个扩展是否是针对一个特定脚本编写的，如果是针对特定脚本编写，自然知道哪一行需要做什么。

> 就以当前的例子，原程序在脚本中只能识别像“20”这样的整数纯数字作为等待时间。而加上扩展后，则变成能够识别“10-30”这种格式作为“10~30范围内随机取值”来作为等待时间。

假如解析之后脚本行第一个参数(延时)是`10-30`，按照目前的程序是无法执行的，因为只能识别整数。那我们在扩展中执行前对该字符串做个参数提取，按照第一个示例或第二个示例设置一下延时，是可以执行的啊？这只是参数放在`脚本中`或`扩展中`的问题。

>  3. 现在的“插件”更像是“mod”而不是“plugin”？
>  通过“外部”脚本来改变原来脚本的内容，进而影响具体的执行内容，这操作是不是有点不太自然“原生”？而现在给我的感觉就像外挂一样对主程序进行hacking，在主程序的视角里基本上对插件所进行的操作是毫无感知的。

在某些情况下，我们确实需要修改具体的执行内容。如果不直接改，也可以像第二个示例一样复制一个事件，修改后手动执行，然后告知程序跳过原事件的执行。

不论这样是否是`mod`还是`plugin`，`改变程序执行流程`，`改变程序执行内容`是为了实现自定义功能而需要实现的目标。引用一下 #115 中的讨论内容：
> 但还有一个痛点，就是KeymouseGo运行scripts过程中，经常由于意外情况，比如说网络卡顿、电脑意外弹窗等等，干扰执行过程，没有按预期方式执行，导致执行结果出错，还是需要人工干预，经常盯住屏幕才行。issues49 提出了此痛点的具体解决方案，但该方案仍未能完全解决此痛点。问题的根源是 KeymouseGo 只管按脚本执行，没有反馈与控制的过程。增加运行过程的用户插件，由插件获取运行状态，解决了反馈问题，但仍无法控制 KeymouseGo 的执行，如果增加根据插件返回结果来控制 KeymouseGo 的后续运行，这个痛点就解决得差不多了。

> 我不是专业的编程人员，这些问题在专业人士面前可能看起来很蠢，还望海涵。

最后，我不是专业人士，这也是我参与贡献的第一个仓库。对于行内的专业人士而言，我的设计可能很糟糕，不规范，存在各种问题(甚至是低级错误)，因此需要在参与贡献的过程中不断学习。如果有什么改进想法，或是我犯了什么错误，望指正。

**Comment by Monomux** [comment]
> 现在的“插件”更像是“mod”而不是“plugin”？

这么一说过程上现在的插件有点像web开发里`request`和`filter`的关系，要执行的事件在执行前后被扩展“捕获”，进行额外操作/滤除/或是内容修改(内容修改是否合适有待商榷，从功能需求的角度上看目前需要这个功能)。

> 可否考虑设计成不在插件里写脚本？
> 结果就是，生成了两份脚本，主程序需要把这两份脚本都读取一遍，然后结合成一个事件列表，再逐一执行。
> 这样做是否会导致主程序的脚本和插件的脚本分离，形成两个文件？

我想我一直没理解你说的关于`两个文件`的问题，以至于专门问了三次。😮

之前一直在关注`文件`，`脚本生成`，很疑惑，然后就一直在想运行时什么时候产生过独立于原脚本的新脚本。我扯的很多内容(脚本解析过程，执行流程，还画了流程图)都是关于执行时没有独立于原脚本事件集的内容额外集合内容产生，可能都是废话，没有逼近你想表达的那个意思。

`在插件里写脚本`，这个现在也可以做到，但肯定不值得提倡，其带来的麻烦你也提到了。但是现在编写插件需要做的事并不是在插件里单纯写几个独立的额外事件，在执行时手动调用穿插插在原脚本执行过程中，这个是你说的`然后结合成一个事件列表，再逐一执行`吧。

上面的第二个示例，插件在事件执行前“捕获”了事件，复制了该事件，对复制的事件参数进行修改，再手动执行事件，返回False，主程序跳过原事件执行。这么做有点`hacking`的感觉，是否合适？从该功能实现的另一个角度看看，如果不通过插件，而是修改事件执行的方法实现功能会怎样。事件通过`execute`方法执行内容，识别参数后进行相应操作，那么需要将参数的解析加入其中。在此以后如果需要另一种参数解析方法又需要怎样(举个极端的例子，延时线性增长)？需要再修改`execute`方法，这样反复修改势必影响开发，一种解决的办法是像现在自定义扩展一样，自己实现一个`ScriptEvent`的子类，重写其`execute`方法再调用父类的方法实现参数的解析，然后程序动态加载覆写的子类。

**Comment by Monomux** [comment]
对之前的回答不满意，遂重新回答一遍。

> 首先，这样做是否会导致主程序的脚本和插件的脚本分离，形成两个文件？

修改一下你前面举的例子：

1. 首先，录制的时候，出来的脚本是不带任何插件内容的。
2. 如果要实现随机等待时间，则需要去插件那，定义好相关参数(如相对于原时间偏移量，或新的等待时间等)。在执行的过程中，根据插件的内容，修改原来的脚本。最终所执行的是根据插件中逻辑修改了内容的原脚本。
3. 结果就是，原有的脚本解析为事件列表，在运行时被动态修改，从而影响执行过程。

至于`两个文件`的问题应该是存在的，如果在插件中直接手写一些**独立于原脚本**的事件，在执行过程中直接显式调用，就相当于你说的`主程序需要把这两份脚本都读取一遍，然后结合成一个事件列表`。但是这样写没必要，因为插件的目的在于修改执行时的效果，而不是再写一份新脚本。至于其它的情况，如插件中执行自定义内容(截屏、文件IO等)、或是流程改变(中途执行另一份脚本、跳转到某一行)，应该不算`生成新脚本`。

> 每次需要执行原定的操作时都必须手动匹配两个脚本来协同工作才能完成预期的目标？

应该说`匹配`的工作还是存在的，如果涉及到对具体行的操作的话。如果说要修改脚本中全部行的某一参数(时间)，就不需要了解原脚本的具体内容了。

> 脚本编辑时的便捷性/可读性是否非常差？就目前主程序所使用的脚本来说，普通用户还是勉强能透过阅读说明文档来快速理解并进行所需的修改。但一旦引入了这个插件，看起来就对非代码技术人员绝缘了。

插件其实是“可选”的，不编写自定义的插件，程序就是正常的顺序执行。而插件的编写，需要一些相关的编程知识。

> 主代码和变量直接混在一起完全是“不可操作”的。

至于这个，不清楚你说的`主代码`和`变量`指什么。

> 而且就算是会编辑代码的专业人员，如果需要两个文件并排，并且要左顾右盼的在脑内模拟合并后的结果来对照修改，想必那体验是绝对的不好的。

这样说的话，为了避免出现这种情况，只能将插件所能实现的内容全部嵌到脚本中去了。打一个比方，要写一个重复执行某语句三次的脚本，像这样:
```
do 3 times:
    mouse move to (800, 600) after 200ms
```
从可读性和编辑难易度上看都要比下面的实现要方便。
```
[200, "EM", "mouse move", [800, 600]]
[200, "EM", "mouse move", [800, 600]]
[200, "EM", "mouse move", [800, 600]]
```

> 现在的“插件”更像是“mod”而不是“plugin”？

说是`mod`也不为过。

> 通过“外部”脚本来改变原来脚本的内容，进而影响具体的执行内容，这操作是不是有点不太自然“原生”？不是应该由主程序提供接口，通过引入插件来扩充主程序所能提供的功能吗？

目前是提供了执行流程各个阶段的接口(脚本执行前，脚本行执行前)等，引入自定义插件，是可以扩充主程序所能提供的功能。

> 比如：就以当前的例子，原程序在脚本中只能识别像“20”这样的整数纯数字作为等待时间。而加上扩展后，则变成能够识别“10-30”这种格式作为“10~30范围内随机取值”来作为等待时间。

目前的解析过程无法识别`10-30`这样的字符串，不过，假如提供了解析时的接口，后续的实现应该如何？事件在执行时必定需要一个确定的时间参数，如果不在现在的插件中指定，就需要再提供一个事件执行的接口。结果是，用户自定义了一个`ScriptEvent`来实现目标需求，覆写了执行方法：
```python
def execution(self):
    # 解析"xx-xx"形式参数的过程，提供一个范围内随机值赋到self.delay
    # ...
    # 原有的事件执行逻辑
    super.execution()
```
这相当于又要写另一个插件。

仔细考虑了一下会产生这些问题的原因，目前的脚本以`json`形式存储，如果不参考说明，会较难弄清楚各参数的含义。现在的扩展所提供的功能是流程控制、运行时参数修改等，假设A为脚本文件能实现的功能集，B为扩展能实现的功能集，两个集合的关系是A∈B。也就是说，举最极端的情况，提供一个空脚本文件，所有的内容全部在扩展里写也是可以实现的。

总结一下，对于普通用户而言：

1. 脚本直接可读性不好(需要查阅文档)
2. 插件与脚本存在功能耦合，产生了一系列衍生问题

既然现在插件功能还没实装，我提出一些想法：

- 修改当前脚本语法，将其转为普通用户也能读懂的形式，如:
用这样的语句
```
mouse move to (800, 600) after 200ms
```
替换当前脚本的语句
```
[200, "EM", "mouse move", [800, 600]]
```

- 将现在的插件所能提供的功能与脚本合并(有点jsp的感觉)

但是这样的话肯定需要重构整个程序非UI逻辑的部分。

**Comment by Monomux** [comment]
如果要保持当前的设计，单论现在脚本与插件的关系，那需要再提供几个接口(事件解析接口以识别脚本中自定义参数，执行接口实现自定义参数对脚本执行内容的修改)，从结果上看，插件依然可以修改执行内容。

**Comment by Monomux** [comment]
现在再想想上面提出的将所有内容综合到一个文件里的方案也不好，因为自定义功能都要写到函数或对象中，无非是定义的位置发生了变化，这样看将自定义功能独立出来反而更好。

另一个问题是plugin或mod的编写，目前是需要有基本的python编程知识才能编写，如果额外编写一些编辑助手之类的可视化生成插件的工具，又会限制其扩展性(因为能实现的功能有限)，目前是没想到很好的解决办法。

**Comment by Monomux** [comment]
### 关于需求实现

> 就以当前的例子，原程序在脚本中只能识别像“20”这样的整数纯数字作为等待时间。而加上扩展后，则变成能够识别“10-30”这种格式作为“10~30范围内随机取值”来作为等待时间。

又看了一遍，参数放在脚本中也是可行的(之前一直在想直接替换第一个延时参数)，下面给出一种实现方法。

在这种扩展下，鼠标脚本格式变为：

```
[200, "EM", "mouse move", [800, 600], [新的时间范围, 坐标偏移范围]]
// for instance
[200, "EM", "mouse move", [800, 600], [[10, 30], [5, 10]]]
```

给出了时间范围后，用随机出的等待时间替换最前面的时间，上面的例子中，该事件在随机等待10\~30s后执行，x坐标随机偏移-5\~5像素，y坐标随机偏移-10\~10像素。

```python
from assets.plugins.Extension import *
from loguru import logger
import random, re, copy
from UIFunc import SW, SH


class MyExtension(Extension):
    def __init__(self, runtimes, speed, thd=None, swap=None):
        super().__init__(runtimes, speed, thd, swap)

    def onrunbefore(self, event, currentindex):
        # 仅改变鼠标有关的事件
        if event.event_type == 'EM':
            # 如果这一行加了附加参数，则修改事件内容
            if event.addon is not None:
                cevent = copy.copy(event)
                timebias, posbias = cevent.addon
                cevent.delay = random.randint(timebias[0], timebias[1])
                cevent.delay = max(cevent.delay, 0)
                # 获取原始坐标
                posx, posy = event.action
                # 相对坐标转绝对坐标
                if not isinstance(posx, int) and not isinstance(posy, int):
                    posx = float(re.match('([0-1].[0-9]+)%', posx).group(1)) * SW
                    posy = float(re.match('([0-1].[0-9]+)%', posy).group(1)) * SH
                posx = int(posx) + random.randint(-posbias[0], posbias[0])
                posy = int(posy) + random.randint(-posbias[1], posbias[1])
                posx = min(max(posx, 0), SW)
                posy = min(max(posy, 0), SH)
                cevent.action = [posx, posy]
                logger.debug(cevent)
                cevent.execute(self.thd)
                # 执行修改过的事件而不是原有事件
                return False
        return True
```

### 关于插件功能

我知道这个插件功能的实现比较野路子，以前没有开发过类似功能。一般来说一个插件系统需要插件管理器管理多插件的注册、监听与调用(没实现)，给出接口供插件实现(已实现)，现在所有的扩展功能都写到了一个文件里，还是有改进空间的，关于这个的讨论可以开个新issue。

**Comment by XYZZQXYZZQ** [comment]
> > ```
> > 2. 如果我要用随机等待时间，则需要去插件那，针对单一特定脚本，生成一个脚本，分别去定义每一行的时间。而这个过程中，原来的脚本不需要做任何的改动。
> > 
> > 3. 结果就是，生成了两份脚本，主程序需要把这两份脚本都读取一遍，然后结合成一个事件列表，再逐一执行。
> > ```
> 
> 按效果来看是在运行时根据插件修改原有的脚本，然后执行修改后脚本的内容。
> 
> 插件本质上就是提供了一些接口，在执行每行脚本前后、每轮执行前后运行一些自定义的内容。上面的示例就是在执行每行脚本前先修改一下实际执行的参数。我上面的示例写的不好，不手动定义每行的具体参数也是可以实现随机参数的功能的。
> 
> 示例:
> 
> 1. 所有行执行时间随机偏离一定范围，最大偏离5ms
> 2. 限制1，2行鼠标范围在x, y轴均随机偏离一定值，最大偏离20px
> 
> ```python
> from assets.plugins.Extension import *
> from loguru import logger
> import random, re, copy
> from UIFunc import SW, SH
> 
> 
> class MyExtension(Extension):
>     def __init__(self, runtimes, speed, thd=None, swap=None):
>         super().__init__(runtimes, speed, thd, swap)
>         # 时间偏移量
>         self.biastime = 5
>         # 绝对坐标偏移量
>         self.biasposx, self.biasposy = 20, 20
>         # 应用随机变化的脚本行
>         self.indexstochange = [0, 1]
> 
>     def onrunbefore(self, event, currentindex):
>         cevent = copy.copy(event)
>         cevent.delay = event.delay + random.randint(-self.biastime, self.biastime)
>         cevent.delay = max(cevent.delay, 0)        
>         if currentindex in self.indexstochange:
>             if event.event_type == 'EM':
>                 posx, posy = event.action
>                 # 相对坐标转绝对坐标
>                 if not isinstance(posx, int) and not isinstance(posy, int):
>                     posx = float(re.match('([0-1].[0-9]+)%', posx).group(1)) * SW
>                     posy = float(re.match('([0-1].[0-9]+)%', posy).group(1)) * SH
>                 posx = int(posx) + random.randint(-self.biasposx, self.biasposx)
>                 posy = int(posy) + random.randint(-self.biasposy, self.biasposy)
>                 posx = min(max(posx, 0), SW)
>                 posy = min(max(posy, 0), SH)
>                 cevent.action = [posx, posy]
>         cevent.execute(self.thd)
>         logger.debug(cevent)
>         # 执行修改过的事件而不是原有事件
>         return False
> ```

![image](https://github.com/taojy123/KeymouseGo/assets/139565930/7e53e40d-09b5-44f9-8ffd-e9219fd9e381)
我尝试把给出的代码做成一个.py文件加入plugin并使用，但不成功，请问我需要怎么做呢？

**Comment by Monomux** [comment]
> 我尝试把给出的代码做成一个.py文件加入plugin并使用，但不成功，请问我需要怎么做呢？

5.1版本改了些内容，你把引用的示例的第四行改成
```python
from Event import ScreenWidth as SW, ScreenHeight as SH
```
试试

**Comment by XYZZQXYZZQ** [comment]
> 

还是一样的...
![image](https://github.com/taojy123/KeymouseGo/assets/139565930/84f43314-6c2f-45c2-9dc3-344e52c2d137)

这是我放在plugins里面的.py文件，麻烦dalao康康
![image](https://github.com/taojy123/KeymouseGo/assets/139565930/ee63f972-3bcd-4008-a903-1947e82c506a)

**Comment by XYZZQXYZZQ** [comment]
还有就是尝试使用这个不能运行的文件之后程序就完全打不开了...

**Comment by Monomux** [comment]
文件本身没问题，我这里用5.1及以上的版本都能运行。另外这版的程序在启动后是不会立即加载plugin的...你看看是不是因为别的问题导致的

**Comment by XYZZQXYZZQ** [comment]
![image](https://github.com/taojy123/KeymouseGo/assets/139565930/e93cbbf4-3ad2-472b-820c-b36315536602)
请问这个“onbeginp”到底是什么啊，我死去活来都弄不明白.... 重装了好多次，重新测试了不知道多少遍，问题都是一模一样

**Comment by Mishasama** [comment]
> 另一个问题是plugin或mod的编写，目前是需要有基本的python编程知识才能编写，如果额外编写一些编辑助手之类的可视化生成插件的工具，又会限制其扩展性(因为能实现的功能有限)，目前是没想到很好的解决办法。

不好意思，有很长一段时间没空来看了……好像已经过去一年了😅

不知道你有没有用过“按键精灵”这个软件？其实它已经提供了一个很好的所见即所得的脚本编辑器范例。
你只要增加一个将源脚本转译成可读的文本，并且加入常用的功能插入工具做成 WYSIWYG 编辑器即可。其余的高级功能可以通过一键切换到源代码模式来手动编写。（如果可以的话最好能在 WYSIWYG 编辑器中解释并显示对应的内容，因为来来去去能用的也就是你提供的接口而已，给接口做个翻译应该不难。实在不行的话直接显示具体无法翻译的代码也可以。）

**Comment by Monomux** [comment]
> 不知道你有没有用过“按键精灵”这个软件？其实它已经提供了一个很好的所见即所得的脚本编辑器范例。 你只要增加一个将源脚本转译成可读的文本，并且加入常用的功能插入工具做成 WYSIWYG 编辑器即可。其余的高级功能可以通过一键切换到源代码模式来手动编写。（如果可以的话最好能在 WYSIWYG 编辑器中解释并显示对应的内容，因为来来去去能用的也就是你提供的接口而已，给接口做个翻译应该不难。实在不行的话直接显示具体无法翻译的代码也可以。）
> 
> 另外我建议你每提供一个接口就给出一个范例来说明其用途/场景或者正确的使用方式。这样也方便你做 WYSIWYG 的 UI 内容。当然，也更加方便大家学习和参与项目的贡献。

感谢指导，之前的思路一直没跳出已有的框架。

**Comment by Monomux** [comment]
> 请问这个“onbeginp”到底是什么啊，我死去活来都弄不明白.... 重装了好多次，重新测试了不知道多少遍，问题都是一模一样

这个是插件类定义的一个方法，报这个错是因为程序无法读到文件定义的类。从你前面发的图里找不出什么错来，你可以发一下相应的日志文件。

**Comment by Monomux** [comment]
> [2023-08-01_04-54-27_596705.log](https://github.com/taojy123/KeymouseGo/files/12229344/2023-08-01_04-54-27_596705.log) log在这里，感谢dalao的帮助！可以弄好的话就太好了

文件名需要与文件内定义的类名相同，这样的话`class MyExtension(Extension):`要改成`class RT(Extension):`。
抱歉抱歉，你上周发那个图片的时候我就应该看出来的。
