### ISSUE TITLE
录制时脚本时，鼠标最后一次点击不被记录

### ISSUE THREAD

**Issue by zhsunlight** [taojy123/KeymouseGo#123]
我从4.0版本开始使用的，发现一个问题一直存在，就是录制脚本时，最后一次鼠标点击没有记录在脚本中（我用的快捷键开启和停止录制）。最后的鼠标移动也很可能是不记录的（这个不太好观察）。

问题重现：测试1：按快捷键开始录制，点击一下鼠标左键，然后停止录制。打开脚本观察是空的。

测试2：如果有两次鼠标点击，之后还有鼠标移动，则第一次鼠标点击及部分鼠标移动会被记录。

录制的脚本文件如下图：
![image](https://user-images.githubusercontent.com/56898908/172042030-d1f20cd5-6702-47b2-b041-e2128316c60d.png)

**Comment by Monomux** [comment]
4.0之前的版本没有录制快捷键，因此录制结束会丢弃最后两条录制内容。现在加入了录制快捷键，但忽略了这个细节，两者使用的逻辑还是相同的，需要分离一下。

**Comment by zhsunlight** [comment]
> 4.0之前的版本没有录制快捷键，因此录制结束会丢弃最后两条录制内容。现在加入了录制快捷键，但忽略了这个细节，两者使用的逻辑还是相同的，需要分离一下。

这么快就找到原因并修正，厉害！
我测试一下。

**Comment by zhsunlight** [comment]
此问题在PR119中得到修正了。https://github.com/taojy123/KeymouseGo/pull/119/commits/7ef7a5fe0637c0486412b6c8047a706eb2190f3a
