### ISSUE TITLE
界面问题

### ISSUE THREAD

**Issue by Mishasama** [taojy123/KeymouseGo#126]
问题1：
现在录制完默认是用时间戳来命名的。但这样压根就没法分辨各个脚本的具体功能。
希望能在UI内提供重命名功能，或者直接打开脚本文件夹并默认选中，方便操作。
****
问题2：
现在录完就录完了，没法便捷地修改。参考问题1，能否加个按钮用于打开脚本文件以便编辑？
****
问题3：
现在只显示正在执行的脚本文件名、第几步、重复次数。信息量感觉有点不足。
是否可以增加显示正在执行的具体内容，及其上下文？
比如将目前的显示内容改成像这样的👇

> `循环次数【3/10】`
> 
> `等待 200ms 后 【鼠标】左键 按下 [1/4]` ——已执行的，文字透明度/底色灰度 60%
> `等待 50ms 后 【鼠标】左键 抬起 [2/4]` ——正在执行的，文字透明度/底色灰度 100%
> `等待 1000ms 后 【键盘】空格 按下[3/4]` ——即将执行的，文字透明度/底色灰度 80%

就显示当前执行的，和上一下一。以便长时间AFK后了解当前的情况。
不必做成命令行那样能滚动的。

**Comment by Mishasama** [comment]
@ZutJoe 界面丑不重要，工具而已，顺手好使就行了👍

另外再提供一个设计想法：
- 选择文件的部分保留列表选择的方式，但仅保留最近`5`个（或者N个，也许可以提供变量让用户自行决定数量）；
然后在列表的最下方永远保持一行“`（……选择其它脚本）`”，用于调用文件选择。

- 至于“`打开文件`”可以考虑将文案更改成“`编辑脚本`”，这样应该能减少歧义。按钮的位置维持在 list box 的旁边就可以了。

- 重命名的话建议使用一个按钮来弹出一个新的对话框窗口，里面包含一个单行文本框和一个确定按钮，使用右上角的X来取消功能即可。这样按钮位置就可以放在“编辑脚本”的旁边了。

这样做既方便切换最近的脚本和进行相关操作，也能让整体的UI更简洁。

**Comment by Monomux** [comment]
> 我在想要不要通过`pyside2`实现

如果像demo一样做成附加的小工具的话，在主程序中需要加一个反馈的过程，在调用工具修改完脚本名称后，主程序关于脚本选择的ComboBox内容需要相应变化；或者这个功能可以直接加到主程序里。

**Comment by ZutJoe** [comment]
> 如果像demo一样做成附加的程序的话，在主程序中需要加一个反馈的过程，在调用子程序修改完脚本名称后，主程序关于脚本选择的ComboBox内容需要相应变化；或者这个功能可以直接加到主程序里。

嗯呢, 是计划这样子的

**Comment by ZutJoe** [comment]
> * 选择文件的部分保留列表选择的方式，但仅保留最近`5`个（或者N个，也许可以提供变量让用户自行决定数量）；
>   然后在列表的最下方永远保持一行“`（……选择其它脚本）`”，用于调用文件选择。

我觉得这个样子是不是不太好? 我认为在旁边加一个`...`的按钮也许会比在下拉框弄一个那个会比较好?
因为我看见选择脚本的那个`ComboBox`其实还有有点富足空间直接放下一个小按钮的

> * 至于“`打开文件`”可以考虑将文案更改成“`编辑脚本`”，这样应该能减少歧义。按钮的位置维持在 list box 的旁边就可以了。

好的

> * 重命名的话建议使用一个按钮来弹出一个新的对话框窗口，里面包含一个单行文本框和一个确定按钮，使用右上角的X来取消功能即可。这样按钮位置就可以放在“编辑脚本”的旁边了。
> 
> 这样做既方便切换最近的脚本和进行相关操作，也能让整体的UI更简洁。

可以, 我尝试一下😂

**Comment by Mishasama** [comment]
> > * 选择文件的部分保留列表选择的方式，但仅保留最近`5`个（或者N个，也许可以提供变量让用户自行决定数量）；
> >   然后在列表的最下方永远保持一行“`（……选择其它脚本）`”，用于调用文件选择。
> 
> 我觉得这个样子是不是不太好? 我认为在旁边加一个`...`的按钮也许会比在下拉框弄一个那个会比较好? 因为我看见选择脚本的那个`ComboBox`其实还有有点富足空间直接放下一个小按钮的
> 

也行……也许这样的设计在代码上会简单一点？
只不过这样做的话就会有3个按钮常驻在一边了。并且“`…`”的可供点击的像素比较少，对点击的精度要求较高。而旁边又有其它按钮，感觉很容易误操作，整体对 触屏/触摸板（或者有身体障碍？） 的用户可能不太友好。
而且无文字说明的话可能对0基础的人不太好理解？（不过估计用这个玩意的人多少都有点基础了？😂）

我是无所谓的，就看这个工具的目标人群定位在哪里了。
如果定位在“所有人”的话，我建议在设计上应该更直观以“便于理解”和“容易操作”。
如果定位是“程序员”之类的专业从业人员的话，那设计可以尽可能精简紧凑，反正“懂的都懂”、“凑合着用”😏

**Comment by ZutJoe** [comment]
* 目前的主界面
![image](https://user-images.githubusercontent.com/54732130/173177719-ca383eab-022c-491e-b326-141beb2de51b.png)

* 点击`...`出现的界面(图标应该会改)
![image](https://user-images.githubusercontent.com/54732130/173177736-395d600d-7ba2-43f9-a29a-3f3ec39d8485.png)

* 重命名的界面
![image](https://user-images.githubusercontent.com/54732130/173177757-4853404f-115d-4aeb-b490-79794764a82f.png)

---

点击`...`按钮之后会默认将当前下拉框的内容保存, 出现在在弹出的界面, 可以直接进行操作, 修改完之后也会反馈到主界面的下拉框中

现在有一个问题https://github.com/taojy123/KeymouseGo/issues/127

**Comment by Mishasama** [comment]
> * 点击`...`出现的界面(图标应该会改)
>   ![image](https://user-images.githubusercontent.com/54732130/173177736-395d600d-7ba2-43f9-a29a-3f3ec39d8485.png)

![image](https://user-images.githubusercontent.com/54498172/173184490-02431771-ef61-40c8-b4ff-42fcb86a8384.png)
这样的设计会不会更好一点？
按钮都安排在底部，在视觉上会比较统一。

另外不知道那个新文件名要不要手动输入扩展名呢？希望不需要……

**Comment by ZutJoe** [comment]
> ![image](https://user-images.githubusercontent.com/54498172/173184490-02431771-ef61-40c8-b4ff-42fcb86a8384.png) 这样的设计会不会更好一点？ 按钮都安排在底部，在视觉上会比较统一。

好的, 可以改一下

> 另外不知道那个新文件名要不要手动输入扩展名呢？希望不需要……

不需要, 你可以加可以不加, 我加了判断

**Comment by ZutJoe** [comment]
修改好了, 如果您想试试可以clone一下代码 https://github.com/ZutJoe/KeymouseGo/tree/Cont'd
顺便还可以测试测试bug😂

**Comment by Monomux** [comment]
现在的主程序支持i18n，新加的部分要不要加入i18n适配

**Comment by ZutJoe** [comment]
> 现在的主程序支持i18n，新加的部分要不要考虑加入i18n适配

好的, 我试试

**Comment by ZutJoe** [comment]
> 现在的主程序支持i18n，新加的部分要不要考虑加入i18n适配

更新完成了 https://github.com/Monomux/KeymouseGo/pull/1

**Comment by Mishasama** [comment]
> 修改好了, 如果您想试试可以clone一下代码 https://github.com/ZutJoe/KeymouseGo/tree/Cont'd 顺便还可以测试测试bug😂

遗憾没有编译能力，只能等成品了😂

据说有BUG？
https://github.com/taojy123/KeymouseGo/pull/128#issuecomment-1154021381

**Comment by ZutJoe** [comment]
> 据说有BUG？ [#128 (comment)](https://github.com/taojy123/KeymouseGo/pull/128#issuecomment-1154021381)

已解决

**Comment by Monomux** [comment]
> 问题3：
> 现在只显示正在执行的脚本文件名、第几步、重复次数。信息量感觉有点不足。
> 是否可以增加显示正在执行的具体内容，及其上下文？

目前的实现：
![Example](https://user-images.githubusercontent.com/70839036/175052377-e9d67c1b-fc8f-4884-bab4-5955ff8877a9.gif)

另外测试时发现 #124 中对延时实现的改动使得运行时无法暂停运行，正在修复。

**Comment by ZutJoe** [comment]
> 目前的实现：
 ![Example](https://user-images.githubusercontent.com/70839036/175052377-e9d67c1b-fc8f-4884-bab4-5955ff8877a9.gif) [ ](https://user-images.githubusercontent.com/70839036/175052377-e9d67c1b-fc8f-4884-bab4-5955ff8877a9.gif)

滚动的好快, 如果是这样提供一个限制条数的或者带滚动条的区域会不会比较好, 用来显示已经执行的

**Comment by Monomux** [comment]
> 滚动的好快, 如果是这样提供一个限制条数的或者带滚动条的区域会不会比较好, 用来显示已经执行的

使用文本编辑框替换标签：
![Example](https://user-images.githubusercontent.com/70839036/175283301-3b5c5939-0802-4f59-af29-27b96472a730.gif)

**Comment by Monomux** [comment]
是否有必要使用一个区域记录执行过的操作？🤔原有的文字提示感觉是`指示运行状态`，而加了文本框后感觉更像是`日志打印`。

**Comment by ZutJoe** [comment]
> 是否有必要使用一个区域记录执行过的操作？🤔原有的文字提示感觉是`指示运行状态`，而加了文本框后感觉更像是`日志打印`。

没太懂啥意思, 如果你觉得可以那就做一下?😂

**Comment by Monomux** [comment]
> 没太懂啥意思, 如果你觉得可以那就做一下?😂

我是指第二次改动后下方的框显示的信息有点多，像一个实时日志窗口。从使用的角度上看似乎用不上这么多信息，使用时更多关注的是执行的状态(当前执行到哪一行，这一行的内容是什么)。

另一方面，如果要再做一个日志“窗口”的话可以再加一些改进：
+ 实时显示录制的内容(录制时)
+ 当脚本本身存在语法问题时，显示大致错误信息
+ 每次执行/录制时，清空文本框内容

![Example (2)](https://user-images.githubusercontent.com/70839036/175470442-c754656e-6672-4001-917d-76044cf9c48b.gif)

**Comment by ZutJoe** [comment]
> 另一方面，如果要再做一个日志“窗口”的话可以再加一些改进：
> 
> * 实时显示录制的内容(录制时)
> * 当脚本本身存在语法问题时，显示大致错误信息
> * 每次执行/录制时，清空文本框内容

可以的, 挺好的
