### ISSUE TITLE
PR问题

### ISSUE THREAD

**Issue by ZutJoe** [taojy123/KeymouseGo#127]
我目前修改的版本是clone @Monomux 的上一个版本
![image](https://user-images.githubusercontent.com/54732130/173177912-07d2c2c8-20bf-48cb-9450-fd1f16dc0aba.png)

我不知道我该如何提交pr:
1.  是应该在当前项目下clone之后将我编写的代码改上去直接提pr
2. 还是等 https://github.com/taojy123/KeymouseGo/pull/119 这个pr被合并之后再提pr

**Comment by Monomux** [comment]
或许可以向我这个分支提PR，合并以后一并等待主仓库合并

**Comment by ZutJoe** [comment]
> 或许可以向我这个分支提PR，合并以后一并等待主仓库合并

但是我现在版本跟不上了你的版本啊😂

**Comment by Monomux** [comment]
那还是等主仓库合并后提PR吧，不然会有潜在的冲突要解决😂

**Comment by ZutJoe** [comment]
难顶
