### ISSUE TITLE
可不可以增加一个简单模式

### ISSUE THREAD

**Issue by gbaoye** [taojy123/KeymouseGo#13]
我按1就会一直连击1 按a就会连击a 在按a就会停止连击 这种简单重复的模式

**Comment by taojy123** [comment]
满足你
这个功能我可以做个小插件形式，放到下个版本的开发计划中去。
最近比较忙，可能要月底或十月份做了

**Comment by gbaoye** [comment]
非常感觉

**Comment by taojy123** [comment]
@gbaoye 
加了一个叫 `MiniCombo` 的小程序

可以在这里查看实现代码
https://github.com/taojy123/KeymouseGo/blob/master/MiniCombo.py

也可以在下载  release 中的 exe 版本
https://github.com/taojy123/KeymouseGo/releases/download/v2.2/MiniCombo.exe
