### ISSUE TITLE
翻译

### ISSUE THREAD

**Issue by ZutJoe** [taojy123/KeymouseGo#130]
既然程序已经适配了英文, 我认为可以将Readme添加一份英文的Readme

**Comment by Monomux** [comment]
可以，其实还想给项目写个简单的wiki来着，现在的Readme有点长。

**Comment by Monomux** [comment]
渣翻了一下Readme，然后按照[standard-readme](https://github.com/RichardLitt/standard-readme)改了一下Readme的结构

**Comment by ZutJoe** [comment]
可以的，我原本的readme已经翻了一半了😂

**Comment by ZutJoe** [comment]
但是它好像有[中文翻译](https://github.com/RichardLitt/standard-readme/blob/master/README.zh-CN.md)版本呀

**Comment by ZutJoe** [comment]
可以的, 那我把我的撤了
