### ISSUE TITLE
关于#135的一些问题

### ISSUE THREAD

**Issue by ZutJoe** [taojy123/KeymouseGo#138]
### 问题

关于 #135 的问题, 我通过一些测试, 我发现了一些问题

* 放大之后, 对不齐的原因
   *  组件的`sizePolicy`中的垂直策略是`Fixed`状态, 不好更改
   *  `QSpinBox`和`QComboBox`两个组件的margin是不一样的, 我认为这是在放大之后产生偏移的主要原因
* 在修改垂直策略之后, 有一点点的变化, 但是变化不大, 因为两个组件的margin是不一样的
* 在统一两个组件的margin之后, 他们的位置会达到预期的效果, 但是会出现下面的状况
   *  `QSpinBox`里面的文字会被挤压
   *  `QComboBox` 的下拉框会由于更改margin之后产生畸变
![image](https://user-images.githubusercontent.com/54732130/178958276-2cf4f2a6-ecc6-4dca-8f0c-e568a823437c.png)
![image](https://user-images.githubusercontent.com/54732130/178958137-88af61c0-0c43-42da-9c44-179d7d8eea6e.png)
![image](https://user-images.githubusercontent.com/54732130/178958166-70be692a-902e-47cd-b6db-b8ada00ceefa.png)
![image](https://user-images.githubusercontent.com/54732130/178958197-28cf362f-3185-41b4-951b-48fea93044ab.png)

### 设想方法
由于上面的一些问题(~~可能自己比较懒, 我觉得通过这样按比例来变化太麻烦了😂~~)
我认为提供两个或是多个界面大小供使用者选择, 会不会更好(~~更方便我们???~~)

**Comment by ZutJoe** [comment]
今天又看了一下之后, 发现是`layoutHorizontalSpacing`和`layoutVerticalSpacing`的值有关系, 现在在想解决方案

**Comment by ZutJoe** [comment]
不行，按照比例放大的方案还是不行，同样分辨率不同尺寸的屏幕按照现在出来的方案是不可行的，有差距，还是两套界面或是多套会更好

**Comment by Monomux** [comment]
我想导致[问题](https://github.com/taojy123/KeymouseGo/pull/135#issuecomment-1166430120)的原因是在groupbox中额外添加了布局。

我基于你的仓库的改动内容加了以下修改:
UiFunc.ui:
+ 打破formlayout，formlayout2的布局
+ 分别选中两个groupbox右键选择“布局-栅格布局”
+ 在groupbox中多出了layout属性，调整参数后保存

正常大小：
![图片](https://user-images.githubusercontent.com/70839036/179384712-2d6203d2-6ca1-479e-889f-d544536f41a1.png)

放大后:

![图片](https://user-images.githubusercontent.com/70839036/179384418-4012c669-e2e6-4e99-9d41-5d0bd705f06b.png)

**Comment by ZutJoe** [comment]
可以, 可以就按照这个样子来

**Comment by ZutJoe** [comment]
可以的话, 看看所有尺寸分辨率的情况吧, 如果没什么问题, 这样也ok

**Comment by Monomux** [comment]
在较大分辨率的情况下没有明显失真

![Windows 7-2022-07-17-13-37-24](https://user-images.githubusercontent.com/70839036/179385434-22bcb481-c3ec-4140-936c-ff211cea04db.jpg)
![Windows 7-2022-07-17-13-30-09](https://user-images.githubusercontent.com/70839036/179385374-1f201b66-9230-4414-81a7-0e222b8930cf.jpg)
![Windows 7-2022-07-17-13-30-37](https://user-images.githubusercontent.com/70839036/179385375-65a8353e-e616-4329-99da-e012093b2ee9.jpg)
![Windows 7-2022-07-17-13-30-59](https://user-images.githubusercontent.com/70839036/179385378-2a14a3b9-04e9-4dc3-a42a-845e843f614f.jpg)
![Windows 7-2022-07-17-13-31-22](https://user-images.githubusercontent.com/70839036/179385379-9f2f6392-0c8f-4402-8082-d6bf00fbb0a6.jpg)

**Comment by ZutJoe** [comment]
> 在较大分辨率的情况下没有明显失真

好的, 可以的, 那您就直接提一个PR😂

**Comment by ZutJoe** [comment]
![image](https://user-images.githubusercontent.com/54732130/179385644-8fc8c295-1f52-49da-8306-2f92ce727787.png)

UIView.py 文件里这个部分可能需要您改一下

**Comment by Monomux** [comment]
提commit前会修改一下。另外这块在QtDesigner改一下更好些，UIView.py每次导出都会被覆盖。

**Comment by ZutJoe** [comment]
> 提commit前会修改一下。另外这块在QtDesigner改一下更好些，UIView.py每次导出都会被覆盖。

可以

**Comment by ZutJoe** [comment]
下面那三个按钮有点违和, 可以把KeymoudeGo里这一段代码给删了

![image](https://user-images.githubusercontent.com/54732130/179386054-7e85f154-97eb-4882-a469-9abff6a35268.png)

**Comment by Monomux** [comment]
> 下面那三个按钮有点违和, 可以把KeymoudeGo里这一段代码给删了

ok
![Windows 7-2022-07-17-14-04-00](https://user-images.githubusercontent.com/70839036/179386164-3ad1fcb7-61c6-4107-9d88-6affe1af95ed.jpg)
![Windows 7-2022-07-17-14-04-21](https://user-images.githubusercontent.com/70839036/179386165-6cd5e219-7ffa-4fd5-9ac4-2465ea6e4ab3.jpg)

**Comment by Monomux** [comment]
提了[PR](https://github.com/ZutJoe/KeymouseGo/pull/1)，如果没有什么要改的，可以reopen #135

**Comment by ZutJoe** [comment]
您直接提我里面嘛😂
我觉得要是弄好了可以直接给这里提的

**Comment by Monomux** [comment]
好的😂

**Comment by ZutJoe** [comment]
> 好的😂

那些我改的有些注释的部分可以直接删了

**Comment by ZutJoe** [comment]
我把pr给交了, 删了一些没用的东西, 这个pr合并了之后dev里面的内容应该也可以合并进来了, 我觉得我们可以发一个新版本了😂
