### ISSUE TITLE
新版本

### ISSUE THREAD

**Issue by ZutJoe** [taojy123/KeymouseGo#144]
* 可以将`dev`分支里面的一些功能合并到`master`里面
* 我们距离上次发布差不多两个月且由80+的commits
* 这次版本更新的功能较多, 是否可以打包成一个大版本?
* 跨平台相关功能, 我认为可以留着后面发布😂

**Comment by Monomux** [comment]
也行，跨平台方面目前只在debian上测试过，mac上有点难处理，而且还有一些[问题](https://blog.csdn.net/qq_38410494/article/details/114994524)

**Comment by ZutJoe** [comment]
虚拟机上可以跑mac吗

**Comment by ZutJoe** [comment]
好的

**Comment by ZutJoe** [comment]
为啥`dev`加到`master`里面后代码好像跑不起来了😂

好像和布局的`py`文件有关系

**Comment by Monomux** [comment]
是的，合并后有冲突，导致ui文件内出现重复定义
