### ISSUE TITLE
界面问题

### ISSUE THREAD

**Issue by ZutJoe** [taojy123/KeymouseGo#148]
如下图:

![image](https://user-images.githubusercontent.com/54732130/184610545-e6991bf7-2700-46ef-8e14-6feefd830ad5.png)

**Comment by 619671442** [comment]
所有的主题都试了,看着眼睛不不舒服,还没有原来的朴实界面舒服

**Comment by ZutJoe** [comment]
已在 #160 中解决界面大小不一致问题

**Comment by Monomux** [comment]
现在的窗口可以靠拖动边缘改变尺寸，但是控件的位置和大小都没有变化，改变后看起来有些别扭。是否可以考虑增加改变尺寸时动态改变控件大小的监听函数，使整体布局总是能铺满整个窗口？或者简单起见，直接锁定窗口尺寸也行。

**Comment by ZutJoe** [comment]
锁定吧

**Comment by ZutJoe** [comment]
> 现在的窗口可以靠拖动边缘改变尺寸，但是控件的位置和大小都没有变化，改变后看起来有些别扭。是否可以考虑增加改变窗口尺寸时动态改变控件大小的监听函数，使整体布局总是能铺满整个窗口？或者简单起见，直接锁定窗口尺寸也行。

已在 https://github.com/taojy123/KeymouseGo/pull/169/commits/d0743c84755e7bf478630d79b6268ff6556562d8 优化
