### ISSUE TITLE
鼠标点击位置建议

### ISSUE THREAD

**Issue by ricepeak** [taojy123/KeymouseGo#152]
强烈建议作者添加一个：鼠标在当前位置，点击左键或者右键的功能，，就是只点击而不给坐标/获取当前坐标值再点击？缺少这个功能实在是太痛苦了

**Comment by ZutJoe** [comment]
给提示吗?

**Comment by ricepeak** [comment]
`pyautogui.position()`这个好像可以实现获取当前坐标，能否引入这个模块？（非计算机专业🤣）

**Comment by ricepeak** [comment]
回复这么快😯

**Comment by ZutJoe** [comment]
有提醒的😂，您需要坐标干嘛，是在录制的时候提示在哪个位置吗？

**Comment by ricepeak** [comment]
不是，是
![image](https://user-images.githubusercontent.com/50504651/185057912-52ff8d20-b8ba-4f6f-be0b-ade42ba89086.png)
从v3.2版本开始用的，十年老粉，我一直想实现这个功能
```
 [2000,"EM","mouse right down",[]],
 [50,"EM","mouse right up",[]],
```
而不用在[]内给定坐标

**Comment by ricepeak** [comment]
之前一直用 v3.2 以为停更了，这个功能实现起来是不是特别麻烦😑

**Comment by Monomux** [comment]
这个功能已经实现了 #39
在当前位置点击时坐标设为[-1, -1]
```
 [2000,"EM","mouse right down",[-1, -1]],
 [50,"EM","mouse right up",[-1, -1]],
```

**Comment by ricepeak** [comment]
……ok，谢谢。
