### ISSUE TITLE
mac无法安装

### ISSUE THREAD

**Issue by Promisey** [taojy123/KeymouseGo#154]
mac 12.4 M1
安装pkg文件的时候打不开，提示“未能完成操作。（com.apple.installer.pagecontroller错误-1。）”
尝试用uppkg解压时，提示“Not a valid package.”

**Comment by Monomux** [comment]
你的pkg文件是哪里来的？现在还没发布支持mac的新版本。

**Comment by Promisey** [comment]
> 请问你的pkg文件是怎么来的？现在还没发布支持mac的新版本。

看说明这样生成的，如果不是这样的话，那现在能在Mac上使用吗，如何使用🙏
1. 安装 Python3
2. pip3 install -r requirements-universal.txt
3. pip3 install pyinstaller
4. pyinstaller -F -w --add-data './assets:assets' KeymouseGo.py

**Comment by Monomux** [comment]
> 看说明这样生成的，运行完在 build 文件夹。

使用pyinstaller打包的程序默认在dist文件夹中。

最近用mac虚拟机测试时遇到了无法监听键盘的问题，别的功能正常。参考pynput的[文档](https://pynput.readthedocs.io/en/latest/limitations.html#macos)，以下条件至少要满足一个：
+ 以root或sudo权限运行程序
+ 将程序添加进辅助功能白名单 
+ 如果Mac版本在Mojave之后，还需要将终端添加进辅助功能白名单，否则无法以命令行形式运行程序

**Comment by Promisey** [comment]
> 



> > 看说明这样生成的，运行完在 build 文件夹。
> 
> 使用pyinstaller打包的程序默认在dist文件夹中，并且是个可执行程序。
> 
> > 如果不是这样的话，那现在能在Mac上使用吗，如何使用🙏
> 
> 目前可以在mac上运行，但只在虚拟机上测试过。
> 
> 最近用mac虚拟机测试时遇到了无法监听键盘的问题。参考pynput的[文档](https://pynput.readthedocs.io/en/latest/limitations.html#macos)，以下条件至少要满足一个：
> 
> * 以root或sudo权限运行程序
> * 将程序添加进辅助功能白名单
> * 如果Mac版本在Mojave之后，还需要将终端添加进辅助功能白名单，否则无法以命令行形式运行程序

非常感谢🙏从终端里用 sudo 命令加 unix 可执行文件的路径，也加了白名单，这样能正常使用。不过 KeymouseGo.app 双击打开的话，是闪退的

**Comment by Monomux** [comment]
> 不过 KeymouseGo.app 双击打开的话，是闪退的

找到问题了，在mac环境下打包后程序识别的工作路径在`/`而不是app所在路径，我将所有使用相对路径的地方全部改成绝对路径后就没有关于路径的报错了。

另外目前的程序样式使用了qt-material，在mac下涉及对`~/.qt_material`内文件的更改，需要提供对该文件夹内容的写权限，否则会有`PermissionError`

```
chmod -R 770 ~/.qt_material
```

已提交修改 c0a2b1c3a9114855f485eb70adc0f7d2f1da3957

**Comment by taojy123** [comment]
@Monomux  厉害啊，已经又支持 Mac 了
