### ISSUE TITLE
游戏内不生效

### ISSUE THREAD

**Issue by ooftf** [taojy123/KeymouseGo#156]
录制的键盘操作在腾讯的游戏内不生效，有什么办法可以解决吗。像按键精灵软件就可以正常生效，你知道它是怎么做到的吗

**Comment by Linranran** [comment]
mark

**Comment by Linranran** [comment]
@ooftf 管理员方式启动！！！！

**Comment by Monomux** [comment]
Keymousego是在系统层模拟键鼠控制的，没办法解决在驱动层捕获输入或是有反外挂机制的游戏，你可以参考一下以往的issue #57 #67 #121
