### ISSUE TITLE
win10 下运行一会就卡死

### ISSUE THREAD

**Issue by MarvinXu** [taojy123/KeymouseGo#158]
![image](https://user-images.githubusercontent.com/7382357/191715685-34ab428d-45ec-41de-b1e3-1fc5bba9aee1.png)

脚本：
```
[
 [0,"EM","mouse left down",["0.738671875%","0.7520833333333333%"]],
 [105,"EM","mouse left up",["0.738671875%","0.7520833333333333%"]]
]
```

**Comment by Liang2527** [comment]
> 你的情况和 #147 的情况相同，在想办法尝试解决

我也有类似的问题，但是我的情况是在一点击“启动” 软件就会闪退，有时候可以运行几分钟，但之后也会莫名其妙闪退。（不会卡死）

**Comment by ZutJoe** [comment]
> > 你的情况和 #147 的情况相同，在想办法尝试解决
> 
> 我也有类似的问题，但是我的情况是在一点击“启动” 软件就会闪退，有时候可以运行几分钟，但之后也会莫名其妙闪退。（不会卡死）

是的，会出现类似的情况，在想办法尝试解决

**Comment by Monomux** [comment]
已尝试修复，目前测试下来没问题，可以尝试下5.1版本。
