### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by ZutJoe** [taojy123/KeymouseGo#161]
由于我在重新设计界面时将 ~~可能~~ 错误的拼写修改了造成了i18n无法正常工作

我在尝试解决这个问题时，发现好像是需要使用qt 的 linguist？？不知道对不对，但是电脑没有相应软件，所以就没有修改这个问题😥

ps: 这个i18n原理是要将 ts -> qm 吗 

![image](https://user-images.githubusercontent.com/54732130/193308336-1ed67410-3b0b-4411-8ae1-fcca5730906f.png)
![image](https://user-images.githubusercontent.com/54732130/193308426-296d9773-c89d-4881-a679-755208673454.png)

**Comment by Monomux** [comment]
linguist软件在qt5-applications包中，使用pip安装后可在`<python env path>/Lib/site-packages/qt5_applications/Qt/bin`找到。

> ps: 这个i18n原理是要将 ts -> qm 吗

在ts文件内完成翻译，由linguist生成qm，再交由QTranslator读取

**Comment by ZutJoe** [comment]
好的，我试一下，谢啦

**Comment by ZutJoe** [comment]
已解决
