### ISSUE TITLE
扩展插件在哪下载

### ISSUE THREAD

**Issue by fgr178707** [taojy123/KeymouseGo#162]
扩展插件在哪下载有没有一个专属下载的地址
仓库链接也行

**Comment by ZutJoe** [comment]
目前的两个基本插件在’assets/plugins’目录下，目前没有收到其他插件文件

如果您有想法制作插件，我们也是欢迎的

**Comment by fgr178707** [comment]
> 目前的两个基本插件在’assets/plugins’目录下，目前没有收到其他插件文件
> 
> 如果您有想法制作插件，我们也是欢迎的

**Comment by fgr178707** [comment]
> 目前的两个基本插件在’assets/plugins’目录下，目前没有收到其他插件文件
> 
> 如果您有想法制作插件，我们也是欢迎的

ok
希望此软件能越做越大
真的太好用了
希望能再多出一点插件

**Comment by ZutJoe** [comment]
您有什么想要的功能插件呢

**Comment by fgr178707** [comment]
> 您有什么想要的功能插件呢
