### ISSUE TITLE
远程服务器桌面执行，关闭远程后不执行是什么原因呢？

### ISSUE THREAD

**Issue by gemgin** [taojy123/KeymouseGo#17]
谢谢

**Comment by taojy123** [comment]
可以把重现步骤已经有价值的输出信息写详细一些。
单从你上面的描述分析，可能是你的远程连线协议在断开时会中断正在运行的进程

**Comment by gemgin** [comment]
怎么捕捉这个中断信息呢？

**Comment by taojy123** [comment]
这个没法手把手教的。
如果方便的话，你可以把你测试环境的远程连接发我，我上去看下。

**Comment by gemgin** [comment]
这个就是本地 3389 远程到服务器 在服务器录制 执行
3389断开，服务器里的脚本不执行，多个服务器测试 都是这样的问题

**Comment by taojy123** [comment]
有一种可能是这样的，因为模拟鼠标点击时基于屏幕坐标的，当远程连接断开后，虚拟的显示屏也就随之销毁了，这时候鼠标点击操作就没法找到正确的位置了。
你可以再试一下，录制一个纯键盘操作的脚本，在远程桌面上运行，然后试试断开后会不会有影响

**Comment by gemgin** [comment]
不是 纯键盘操作 一样，断开就暂停了

**Comment by taojy123** [comment]
那还蛮有意思的，确认一下是“暂停” 而不是 “终止”？
也就是说重新连接后还会继续往下执行？

**Comment by taojy123** [comment]
我开了个 win 2019 系统的服务器，测试了一下。
通过远程连接在远端桌面录制一个脚本，脚本的内容是 “先点击窗口a，10s 后点击窗口b”。
启动脚本后，看到窗口a被立马点击了，然后立刻断开远程连接
过了半分钟后再次连接，查看到远端桌面上窗口b已经处于 active 状态，说明10s后的点击操作确实执行了。
不过我是用阿里云默认的网页版的远程连接，不是 windows 的“远程桌面连接”工具。
你也可以试下其他的远程工具，比如 vnc 等

**Comment by gemgin** [comment]
我试试网页版

**Comment by gemgin** [comment]
网页版的 是正常的，断开可以正常执行，神奇了
为什么RDP  3389就不行呢

**Comment by taojy123** [comment]
看下这篇文章
https://www.lijun.me/266.html
不知你这是不是类似的情况

**Comment by gemgin** [comment]
都试了下 ，不是哪种情况，不是注销的问题

**Comment by taojy123** [comment]
@gemgin 
> 谢谢

哥们 咋把留言全删了？
找到问题原因了？
