### ISSUE TITLE
json格式错误

### ISSUE THREAD

**Issue by jekran** [taojy123/KeymouseGo#170]
请问楼主脚本怎么变成json文件

**Comment by ZutJoe** [comment]
我们目前支持的是txt文件格式的脚本文件，目前还没有适配json格式的文件

**Comment by jekran** [comment]
> 我们目前支持的是txt文件格式的脚本文件，目前还没有适配json格式的文件

emm，txt里面不是json格式的吗

**Comment by jekran** [comment]
[
 [3000, "EM", "mouse right down", ["0.05208%", "0.1852%"]],
 [50,   "EM", "mouse right up",   ["0.05208%", "0.1852%"]],
 [1000, "EK", "key down",         (70, 'F', 0)],
 [50,   "EK", "key up",           (70, 'F', 0)],
 [100,  "EM", "mouse left down",  ["0.2604%", "0.4630%"]],
 [100,  "EM", "mouse move",       ["0.2604%", "0.5556%"]],
 [100,  "EM", "mouse left up",  ["0.3125%", "0.5556%"]],
 [100,  "EX", "input",           "你好 world"]
]  这样格式的文件我按脚本执行的话会报json错误

**Comment by ZutJoe** [comment]
是json格式的，但是是以txt的文件来读的，程序内部有解析

**Comment by Monomux** [comment]
> 是json格式的，但是是以txt的文件来读的，程序内部有解析

还是按照json文件读的，只是后缀是txt，而且现在只用了数组，没有使用键值对。
https://github.com/taojy123/KeymouseGo/blob/0313f8a8b547de6c3880eb059588f1c8e88436c7/UIFunc.py#L622

**Comment by jekran** [comment]
> > 是json格式的，但是是以txt的文件来读的，程序内部有解析
> 
> 还是按照json文件读的，只是后缀是txt，而且现在只用了数组，没有使用键值对。
> 
> https://github.com/taojy123/KeymouseGo/blob/0313f8a8b547de6c3880eb059588f1c8e88436c7/UIFunc.py#L622

是的，我看到这里也有点疑惑

**Comment by Monomux** [comment]
通过debug发现错误就出在这一行，但是采用录制得到的脚本格式与这里使用的脚本格式一致，会不会是编码不同导致的问题

**Comment by Monomux** [comment]
是脚本范例的问题，我改成这样就可以执行了
```
[
    [3000, "EM", "mouse right down", ["0.05208%", "0.1852%"]],
    [50, "EM", "mouse right up", ["0.05208%", "0.1852%"]],
    [1000, "EK", "key down", [70, "F", 0]],
    [50, "EK", "key up", [70, "F", 0]],
    [100, "EM", "mouse left down", ["0.2604%", "0.4630%"]],
    [100, "EM", "mouse move", ["0.2604%", "0.5556%"]],
    [100, "EM", "mouse left up", ["0.3125%", "0.5556%"]],
    [100, "EX", "input", "你好 world"]
]

```

**Comment by ZutJoe** [comment]
> > 是json格式的，但是是以txt的文件来读的，程序内部有解析
> 
> 还是按照json文件读的，只是后缀是txt，而且现在只用了数组，没有使用键值对。
> 
> https://github.com/taojy123/KeymouseGo/blob/0313f8a8b547de6c3880eb059588f1c8e88436c7/UIFunc.py#L622

行吧😂

**Comment by jekran** [comment]
> 是范例的问题，改成这样就可以执行了
> 
> ```
> [
>     [3000, "EM", "mouse right down", ["0.05208%", "0.1852%"]],
>     [50, "EM", "mouse right up", ["0.05208%", "0.1852%"]],
>     [1000, "EK", "key down", [70, "F", 0]],
>     [50, "EK", "key up", [70, "F", 0]],
>     [100, "EM", "mouse left down", ["0.2604%", "0.4630%"]],
>     [100, "EM", "mouse move", ["0.2604%", "0.5556%"]],
>     [100, "EM", "mouse left up", ["0.3125%", "0.5556%"]],
>     [100, "EX", "input", "你好 world"]
> ]
> ```

确实，不过single_run这个方法接收脚本解析结果那得多加个值

**Comment by jekran** [comment]
> > 是范例的问题，改成这样就可以执行了
> > ```
> > [
> >     [3000, "EM", "mouse right down", ["0.05208%", "0.1852%"]],
> >     [50, "EM", "mouse right up", ["0.05208%", "0.1852%"]],
> >     [1000, "EK", "key down", [70, "F", 0]],
> >     [50, "EK", "key up", [70, "F", 0]],
> >     [100, "EM", "mouse left down", ["0.2604%", "0.4630%"]],
> >     [100, "EM", "mouse move", ["0.2604%", "0.5556%"]],
> >     [100, "EM", "mouse left up", ["0.3125%", "0.5556%"]],
> >     [100, "EX", "input", "你好 world"]
> > ]
> > ```
> 
> 确实，不过single_run这个方法接收脚本解析结果那得多加个值

感谢两位大佬

**Comment by ZutJoe** [comment]
> > 是范例的问题，改成这样就可以执行了
> > ```
> > [
> >     [3000, "EM", "mouse right down", ["0.05208%", "0.1852%"]],
> >     [50, "EM", "mouse right up", ["0.05208%", "0.1852%"]],
> >     [1000, "EK", "key down", [70, "F", 0]],
> >     [50, "EK", "key up", [70, "F", 0]],
> >     [100, "EM", "mouse left down", ["0.2604%", "0.4630%"]],
> >     [100, "EM", "mouse move", ["0.2604%", "0.5556%"]],
> >     [100, "EM", "mouse left up", ["0.3125%", "0.5556%"]],
> >     [100, "EX", "input", "你好 world"]
> > ]
> > ```
> 
> 确实，不过single_run这个方法接收脚本解析结果那得多加个值

有兴趣我们可以自己提个pr哦👀
