### ISSUE TITLE
录制的过程中展示框不出现录制的脚本

### ISSUE THREAD

**Issue by ZutJoe** [taojy123/KeymouseGo#172]
之前的版本是有的 `v5.0`，但是当前`master`分支下运行的代码是没有的

**Comment by Monomux** [comment]
引入跨平台功能时漏加了语句，我在做插件功能的时候顺带修复下吧。

![图片](https://user-images.githubusercontent.com/70839036/195623575-b206bd82-be3d-479f-9129-051bd1228f49.png)

**Comment by ZutJoe** [comment]
好的
