### ISSUE TITLE
能否添加轮询N分钟执行一次的功能

### ISSUE THREAD

**Issue by Clark1Yang** [taojy123/KeymouseGo#177]
能否添加轮询N分钟执行一次的功能

**Comment by ZutJoe** [comment]
`在脚本末尾添加一个延时且鼠标在原位的操作再设置执行的次数` 可以实现您描述的功能（我觉得

**Comment by Clark1Yang** [comment]
非常好用的工具，已通过脚本实现此功能，不过还是希望UI能提供功能窗口。

**Comment by Clark1Yang** [comment]
> 

嗯嗯，非常感谢，和我预想的一样。

**Comment by ZutJoe** [comment]
没事的，感谢您对app的认可
