### ISSUE TITLE
keymousego在deepin linux下运行无反应

### ISSUE THREAD

**Issue by sllkff** [taojy123/KeymouseGo#178]
操作系统是deepin linux   20.7.1版本 ，下载的是5.1 releases  linux版本，直接运行无反应，是我操作不对还是程序问题？

**Comment by Monomux** [comment]
是程序的问题，Pyinstaller在linux环境下打包不会将libc依赖一并打包而是直接链接操作系统的库([参考](https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible))，可能是您的系统与打包时的系统使用的依赖版本不同导致报错，目前的解决方法是clone项目后手动打包。

**Comment by debuggerx01** [comment]
@sllkff 
https://github.com/debuggerx01/KeymouseGo/actions/runs/3358317205
![image](https://user-images.githubusercontent.com/19624835/198925182-bf5f8e10-7423-4a1b-b00a-b3ce25d5ac74.png)

**Comment by sllkff** [comment]
非常感谢，已经能运行
