### ISSUE TITLE
不能下载

### ISSUE THREAD

**Issue by Z-J-Fei** [taojy123/KeymouseGo#18]
不能下载啊，需要fanqiang吗？我看见好像是亚马逊的服务器

**Comment by taojy123** [comment]
一般来说不用翻的，但因为服务器是在海外还是可能出现间歇性访问不了。
回头我加一个国内的下载地址吧

**Comment by taojy123** [comment]
国内下载地址
http://qiniu.athenagu.com/docs/KeymouseGo_x64.exe

**Comment by Z-J-Fei** [comment]
谢谢你，我昨天用服务器下载了，只不过下载的慢，十几k的样子。感谢感谢。用了下贼好用。

**Comment by taojy123** [comment]
哈哈 谢谢认可
