### ISSUE TITLE
[potential bug] 更改快捷键后无法正常运行

### ISSUE THREAD

**Issue by iopav** [taojy123/KeymouseGo#184]
笔记本没有f9 因此将执行中断改为中键

- 已有脚本运行只能跑3个action
- 录制脚本会自动结束，并且脚本为空
- 其他未复现问题：循环运行无法中断，只能强行结束程序……
![image](https://user-images.githubusercontent.com/27114852/200176323-a4217f8b-f2eb-4455-bb8b-c7787713b01b.png)

感谢大大的code

**Comment by iopav** [comment]
![image](https://user-images.githubusercontent.com/27114852/200176513-fd15391e-95a7-4b66-949d-b8754f6aa0c8.png)

**Comment by Monomux** [comment]
判断热键时的条件有点问题，已提交更改 4a4d56477669039e80b614d30983f71a5b387300 。
