### ISSUE TITLE
调试的时候报错， win11 python3.9

### ISSUE THREAD

**Issue by seualphagit** [taojy123/KeymouseGo#187]
(<class 'ImportError'>, ImportError("cannot import name 'cpyHook' from partially initialized module 'pyWinhook' (most likely due to a circular import)

**Comment by ZutJoe** [comment]
这个模块目前不能通过`pip` 下来，需要通过本地来加载 
通过这个网站下载相关模块，再从本地安装 https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by ZutJoe** [comment]
[pyWinhook-1.6.2-cp310-cp310-win_amd64.zip](https://github.com/taojy123/KeymouseGo/files/10100216/pyWinhook-1.6.2-cp310-cp310-win_amd64.zip)

或者您可以直接下载这个压缩包，然后通过这个方式 https://www.cnblogs.com/emanlee/p/14333005.html  ，如果不想进路径，可以直接在`*.whl`文件前加上文件路径
