### ISSUE TITLE
关于scroll的监听

### ISSUE THREAD

**Issue by DOCCA0** [taojy123/KeymouseGo#19]
您好，我借鉴您的思路自己做了一遍 增加了scroll的监听，但是运行后scroll的动静很小 根本就不能还原scroll的操作，请问这是为什么？？

**Comment by taojy123** [comment]
你也是使用 pynput 监听和重放的是吧。
这个可能是 pynput 的问题，我之前也想开发 scroll 功能的，也是遇到坑放弃了。
你可以再想象办法如果能解决的话，给我 PR 哈。
我觉得可以先试下单独用 pynput 监听鼠标滚轮向下滚 3 次，然后看监听到的内容对象是如果的。
再使用 pynput 模拟滚轮向下动作。看下这中间的误差发生在哪里。
比如你模拟滚轮向下 3 次，实际屏幕只向下走了原来的一半。那以后就把录制的 scroll 脚本中次数乘以 2，当然这是想象中的理想情况。实际可能需要做更多的实验和研究。

**Comment by DOCCA0** [comment]
scroll记录的-1和+1代表的是鼠标滚轮滑动一格，但是在运行脚本的时候scroll需要的是像素变化，我因此尝试了pyautogui和win32api，需要的都是像素值，卡了很久，放弃了
另外，问个题外话，您用什么打包的啊才10M，我用pyinstaller打包出来40M

**Comment by taojy123** [comment]
一般 pyinstaller 打出来的是 10M 差不多的，你是不是把 pywin32 这些也不小心打包进去了。
另外我安装的是最新版本的 pyinstaller，系统是 win7
