### ISSUE TITLE
由于输入法智能调频导致脚本回放时文字偶尔错误的问题

### ISSUE THREAD

**Issue by GoogleDong** [taojy123/KeymouseGo#197]
由于输入法智能调频导致脚本回放时文字偶尔错误，（或者因为中英文输入法人为切换，录屏时输入法与回放时输入法不一致导致输入错误）
考虑使用 [100, "EX", "input", "别调频啦!"]方式来规避该问题，
但是尝试了多种输入方式，脚本录制时都没有触发 [100, "EX", "input", "....."]事件。

请问屏幕录制时，如何操作文本输入，才可 触发 100, "EX", "input", "....."] 事件？

非常感谢！

**Comment by Monomux** [comment]
目前程序只会录制键鼠操作事件，录制时不会触发[100, "EX", "input", "....."]事件。如果要使用，可以手动修改脚本加入此内容。

**Comment by GoogleDong** [comment]
> 目前程序只会录制键鼠操作事件，录制时不会触发[100, "EX", "input", "....."]事件。如果要使用，可以手动修改脚本加入此内容。

谢谢~
