### ISSUE TITLE
你好，能解释下操作本文内的含义吗？

### ISSUE THREAD

**Issue by datourezi** [taojy123/KeymouseGo#2]
额，大概我已经知道了，比如
['EK', 'key down', 256, 1, 72, 'H', 'WindowsForms10.EDIT.app.0.11c7a8c', 2888450]
1是按键间隔，72是H对应的ASCII码，唯一就是最后一个2888450，有点疑问？

**Comment by datourezi** [comment]
额，大概我已经知道了，比如
['EK', 'key down', 256, 1, 72, 'H', 'WindowsForms10.EDIT.app.0.11c7a8c', 2888450]
1是按键间隔，72是H对应的ASCII码，唯一就是最后一个2888450，有点疑问？

**Comment by taojy123** [comment]
这有点久远了，我得翻一翻代码才能回忆起来。
源码中  #238行
record.append(['EK',event.MessageName,event.Message,event.Time - ttt,event.KeyID,event.Key,cname,dcid])


cname = win32gui.GetClassName(rhwnd)
dcid = win32gui.GetDlgCtrlID(rhwnd) 
这两个参数是 windows 的窗口句柄，主要是给在 “后台模式” 用的，在 #375行处有用到这个。

PS: 不过键盘事件，还不支持后台模式，所以上面这个例子的最后两个数据暂时是没用的

**Comment by datourezi** [comment]
好的，那就没事了，我主要修改操作文件让操作更灵活。

**Comment by datourezi** [comment]
谢谢提供的神器，哈哈哈

**Comment by pozhuzi** [comment]
想问一下次数好像仅限定于0-100，可不可以改为更大的数

**Comment by taojy123** [comment]
> 想问一下次数好像仅限定于0-100，可不可以改为更大的数

你好，你说的次数指的是哪里？能不能把对应的代码一起贴出来下

**Comment by pozhuzi** [comment]
描述：运行exe文件时，修改执行次数超过100的，都会被默认为100。
 `self.stimes = wx.SpinCtrl(id=wxID_FRAME1STIMES, initial=0, max=100 ` //Frame1.py (102行)，所以我怀疑是不是这里限制了次数
