### ISSUE TITLE
发布的二进制文件chrome浏览器报毒

### ISSUE THREAD

**Issue by rayxuln** [taojy123/KeymouseGo#20]
如图
![image](https://user-images.githubusercontent.com/20488881/74522540-55979280-4f56-11ea-8ad8-96f434c24dd8.png)

**Comment by taojy123** [comment]
因为程序会有模拟用户操作的功能，所以确实会有被人用于不法用途的可能性。chrome 报读可以忽略，或通过其他方式下载。
