### ISSUE TITLE
命令行工具无法使用

### ISSUE THREAD

**Issue by Zhang-Jia-Qi** [taojy123/KeymouseGo#207]
我直接下载的release版本KeymouseGo，重命名为KeymouseGo.exe后和其生成的脚本文件夹等一起移动到Program Files文件夹。
cd到对应的文件夹以后，使用.\KeymouseGo scripts/xxx.txt，没有反应，在脚本中加一个打字到写字板的动作后，证实脚本并未运行。
在应用中以相同的参数运行相同脚本，一切正常，且可以正常输出预定文字。
请问这是我的操作不正确还是存在某些bug？
环境：windows10 x64

**Comment by Zhang-Jia-Qi** [comment]
运行命令行时使用的是新版的windows powershell，用的是管理员权限运行。

**Comment by Monomux** [comment]
duplicate of #190 
这个问题在开发分支已经修复了，但是目前新功能还没完全开发完，暂时不能发布包含新特性的大版本。
我先将这几个月里修的小bug单独加进主分支，在这几天里发布个小版本吧。
目前要命令行运行可以先回退5.0版本。

**Comment by Monomux** [comment]
新发布版本中已修复此问题。
