### ISSUE TITLE
对拖动这个操作执行的不是很好

### ISSUE THREAD

**Issue by ojawo** [taojy123/KeymouseGo#21]
录制下来拖动的操作后，再执行时，不是百分百复现

**Comment by taojy123** [comment]
录制的动作其实只要鼠标按下点坐标，鼠标抬起点坐标，中间的拖动过程，也就是 mousemove 动作没有被记录

**Comment by taojy123** [comment]
我回头研究下，看看能不能把拖动轨迹作为录制的可选项。

**Comment by taojy123** [comment]
我先关了哈，回头做新 feature 开发
