### ISSUE TITLE
mac版本无法打开 本编码unicode (utf-8)不适用

### ISSUE THREAD

**Issue by yong1983** [taojy123/KeymouseGo#214]
系统：macos ventura 13.2.1  打开app显示：未能打开文稿 KeymouseGo_v5_1_1-mac 文本编码unicode (utf-8)不适用  网上查了教程选择为“中文（GB 18030）也没有用

**Comment by yong1983** [comment]
求解答谢谢

**Comment by Monomux** [comment]
打包的程序是Unix executable文件，可以尝试使用控制台打开，这里系统应该是将文件当成文稿了。
我修改了一下打包命令，你可以在[这里](https://github.com/taojy123/KeymouseGo/actions/runs/4319382889)或是[release](https://github.com/taojy123/KeymouseGo/releases/tag/v5.1.1)中找到打包的app程序。

**Comment by yong1983** [comment]
谢谢🙏
