### ISSUE TITLE
window提示木马,是否是打包工具问题

### ISSUE THREAD

**Issue by anterchen** [taojy123/KeymouseGo#22]
已检测到威胁::Trojan:Win32/Zpevdo.A
警报级别:严重

**Comment by taojy123** [comment]
pyinstaller (http://www.pyinstaller.org/) 打包的，所用到的全部东西都是开源的，应该没有问题，放心用。
不放心的话也可以 clone 源代码自己用 pyinstaller 打包一下，也比较方便的。

**Comment by anterchen** [comment]
好的,我也感觉应该是window误报了
