### ISSUE TITLE
占用大量内存资源

### ISSUE THREAD

**Issue by jack01-make** [taojy123/KeymouseGo#23]
你好，为什么我运行python脚本后，占用了大量的内存资源，我12G的内存被飙到百分之九十多，我一直都是保持在60%以下的

**Comment by taojy123** [comment]
我试了下运行源代码的时候内存还是比较正常的，你可以具体排查下你那里哪部分的代码导致的内存升高。

**Comment by jack01-make** [comment]
我用IDLE打开或者直接运行都没问题。可能是VS code跟一些模块有冲突吧，打开后挂在后台，我在任务管理器里看到Python的内存占用量一直在增加，越来越大。直接用IDLE打开没问题

**Comment by taojy123** [comment]
哦哦 ，你通过 vs code 启动的。我倒没试过这个。回头我也用 vs code 试下，如果我这么能重现的话，可以进一步定位问题 😄

**Comment by jack01-make** [comment]
![image](https://user-images.githubusercontent.com/61861432/77157631-b88fc280-6adc-11ea-8e76-441868623a99.png)
我监控了一下进程，发现是我昨晚设置的路径的问题，我把它删掉后就没问题了
