### ISSUE TITLE
是否可以 不指定坐标 连续点击？

### ISSUE THREAD

**Issue by nAnderYang** [taojy123/KeymouseGo#246]
现在好像必须要坐标 才能完成点击？指定到鼠标位置连续点击是否可行？请指教~

**Comment by Monomux** [comment]
将坐标设置为`[-1,-1]`即可令鼠标在当前停靠的位置进行操作。
https://github.com/taojy123/KeymouseGo/issues/39#issuecomment-706483534

**Comment by nAnderYang** [comment]
好的明白, 谢谢
