### ISSUE TITLE
录制好的脚本能指定时间点执行吗？

### ISSUE THREAD

**Issue by taomylife521** [taojy123/KeymouseGo#25]
这个只适用于电脑吗？手机端能不能支持？

**Comment by taojy123** [comment]
目前没有指定时间的功能
 
这个只能在电脑上使用 手机上用不了

**Comment by taojy123** [comment]
我刚才想了一下目前的版本功能 变通一下其实也可以实现定时执行，就是比较麻烦一点。
我们录制好的脚本文件可以手动修改其中每个动作之间的时间间隔，你可以将第一个动作的时间间隔改的足够长。
比如现在是7点，你希望8点时脚本自动运行，那么就就将第一个动作的间隔改为1个小时。然后现在直接启动脚本，理论上到8点时就会开始你想要的自动操作😄

**Comment by johnw2018** [comment]
可以结合计划任务程序，执行命令行版本啊

**Comment by taojy123** [comment]
> 可以结合计划任务程序，执行命令行版本啊

这个思路也不错
