### ISSUE TITLE
修改scripts文件报错

### ISSUE THREAD

**Issue by Vlgar** [taojy123/KeymouseGo#252]
我在对录制后的script文件进行修改后运行报错了。我只改了文件中的时间间隔，如下：
an error occurred while parsing script
expecting value:line 1 column1(char 0)
----
an error occurred during runtime
local variable 'module_name' referenced before assignment
---
failed

**Comment by Monomux** [comment]
你可以发一下有误的脚本以供参考。

**Comment by Vlgar** [comment]
> 

谢谢你的回复，我知道原因了。我这边会自动加密这个生成脚本文件，从而导致解析文件出错。
