### ISSUE TITLE
关于点击事件的坐标问题

### ISSUE THREAD

**Issue by FranklinDX3906** [taojy123/KeymouseGo#26]
您好，首先感谢您的这个项目，对我帮助很大。
我在1920*1080分辨率的电脑上使用可执行文件时碰到一个问题，鼠标点击事件记录的像素坐标位置与实际操作时的位置有一定的误差，纵坐标误差大概有7到10左右，导致有些操作会中断，希望有朝一日能修改一下，不过可以通过修改本地txt文件的方式继续使用。
最后还是感谢您的项目！

**Comment by taojy123** [comment]
谢谢~ 之前确实遇到过坐标误差的问题，但那个主要是设置了屏幕缩放后才会出现，并且是按比例偏差的。你描述的这种情况只有纵坐标误差，并且是固定的 7 到 10px，确实有点费解。方便提供一些更多的细节，有助于排查和定位问题吗

**Comment by FranklinDX3906** [comment]
您好，经过查证发现是我的电脑未修改缩放、一直处于125%的缘故，抱歉浪费您的时间了

**Comment by taojy123** [comment]
哈哈，没关系~ 果然是这个原因。

**Comment by taojy123** [comment]
@FranklinDX3906  我刚才收到的一笔捐赠，请问是你吗？

**Comment by FranklinDX3906** [comment]
是我的十块钱，聊表歉意，顺便支持一下

---原始邮件---
发件人: "taojy123"<notifications@github.com&gt;
发送时间: 2020年4月10日(周五) 晚上6:23
收件人: "taojy123/KeymouseGo"<KeymouseGo@noreply.github.com&gt;;
抄送: "张毅恒"<993628121@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [taojy123/KeymouseGo] 关于点击事件的坐标问题 (#26)




 
@FranklinDX3906  我刚才收到的一笔捐赠，请问是你吗？

**Comment by taojy123** [comment]
谢谢支持

**Comment by FranklinDX3906** [comment]
没事，祝万事顺利



---原始邮件---
发件人: "taojy123"<notifications@github.com&gt;
发送时间: 2020年4月10日(周五) 晚上6:35
收件人: "taojy123/KeymouseGo"<KeymouseGo@noreply.github.com&gt;;
抄送: "张毅恒"<993628121@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [taojy123/KeymouseGo] 关于点击事件的坐标问题 (#26)




 
谢谢支持
