### ISSUE TITLE
兼容性问题win10，win11可以运行，win7运行

### ISSUE THREAD

**Issue by liang6163068** [taojy123/KeymouseGo#267]
![200d76191e5660caa1a5afda3e177bf](https://github.com/taojy123/KeymouseGo/assets/23067954/6b70301c-b170-4676-b9de-408ec928acec)
win7启动exe后，报错failed to start embedded python interpreter，这是什么原因呢，打包的问题吗

**Comment by Monomux** [comment]
具体的情况可以说的详细一点吗？比如程序是从release下载的还是自己打包的。

**Comment by liang6163068** [comment]
程序是release版本代码下载后，自行修改了一点功能后自己打包生成的exe

**Comment by Monomux** [comment]
确认一下打包时使用的python版本是否为`python3.8`及以下版本？

**Comment by liang6163068** [comment]
打包使用的版本为3.11，这必须是3.8版本吗

**Comment by Monomux** [comment]
·python3.9·及以上的版本不支持win7，要保证能在win7上运行的话需要使用`python3.8`及以下版本。

**Comment by liang6163068** [comment]
好的好的，我再试试，非常感谢

**Comment by liang6163068** [comment]
![image](https://github.com/taojy123/KeymouseGo/assets/23067954/5721e88d-ab54-439f-8ca5-789aa2d6dcd0)
大佬再帮忙看下，现在用python37编译后在win7系统出现这个错误，其他正常

**Comment by Monomux** [comment]
在打包之前，程序是否可以通过`python KeymouseGo.py`启动？如果可以，可以提供打包后程序后以命令行形式运行程序的输出吗？如果不行，可以提供控制台的输出吗？

**Comment by liang6163068** [comment]
解决了win7系统下pyside6有问题，已经改到pyside2.0版本了
