### ISSUE TITLE
使用文档中添加extension会报错

### ISSUE THREAD

**Issue by Skylovzxc** [taojy123/KeymouseGo#269]
请问有没有群之类的，可以帮忙看一下怎么解决吗

**Comment by Skylovzxc** [comment]
根据扩展的文档中，复现Myextension不成功。

**Comment by Monomux** [comment]
使用的程序版本是？

**Comment by Skylovzxc** [comment]
您好，复现的时候使用的是5.1.1release版本，Feb 11 2023 win.exe 这个版本。  同时，我注意到文档中说 只适用于5.1及以下，5.1.1是不是就不适用了？   我随后去尝试5.1版本的试一试

**Comment by Monomux** [comment]
只有5.0版本能跑那个示例，5.1版本改了点内容，只能通过label实现跳转了。

**Comment by Skylovzxc** [comment]
好的，我试试5.0版本

**Comment by Skylovzxc** [comment]
您好，我想请问一下，如何把pyautogui  import进去呀？   我尝试用文档中的
 from KeymouseGo import add_lib_path
add_lib_path([
    os.path.join(os.getcwd(), "pyautogui")
])  
import pyautogui
 但是加入 add_lib_path 以后，再开始录制，就不会记录行为了。  请问这是怎么回事呀？

**Comment by Monomux** [comment]
> 但是加入 add_lib_path 以后，再开始录制，就不会记录行为了。 请问这是怎么回事呀？

打包的windows版本里没有附带上这个库，因此会报错导致程序初始化失败，正常功能无法使用。要使用额外的库，目前最方便的方式是下载源码并在python环境中装上所需的库再进行开发使用，抱歉。

**Comment by Skylovzxc** [comment]
哦哦好的，谢谢你
