### ISSUE TITLE
shift 无法被正确的重放

### ISSUE THREAD

**Issue by taojy123** [taojy123/KeymouseGo#27]
脚本：
```
[
 [1000,"EK","key down","shift"],
 [1000,"EK","key down","down"],
 [200,"EK","key up","down"],
 [1000,"EK","key up","shift"]
]
```

理论上运行时会向下选择一行

实际运行时只有光标向下移动了一行，说明 shift 没有生效

**Comment by linwolfer** [comment]
Ctrl+C 和 Ctrl+V 同样无效，就是无法复制和粘贴。请检查，谢谢

非常好用、实用的一款软件，特别是脚本运行这个功能太赞了。如果能识别窗口（句柄）就更酷了。

**Comment by taojy123** [comment]
@linwolfer  嗯 带功能的组合键好像是有些问题，之前也有人反应过所以建了这个 issue。
初步分析是 pynput 的 bug，正在看 pynput 的源码和实现原理，看下能不能 fix 它。

**Comment by linwolfer** [comment]
> @linwolfer 嗯 带功能的组合键好像是有些问题，之前也有人反应过所以建了这个 issue。
> 初步分析是 pynput 的 bug，正在看 pynput 的源码和实现原理，看下能不能 fix 它。

嗯，辛苦了。加油 😀

**Comment by gaodi16366** [comment]
组合键基本都无效

**Comment by linwolfer** [comment]
> 组合键基本都无效

不，Ctrl+C 可用

**Comment by taojy123** [comment]
v3.0 版本修复了此问题。
https://github.com/taojy123/KeymouseGo/releases/tag/v3.0
