### ISSUE TITLE
您好，请问怎么录制回车键呢？谢谢！

### ISSUE THREAD

**Issue by PiPiNam** [taojy123/KeymouseGo#28]
您好，请问怎么录制回车键呢？谢谢！
我发现按下回车键就终止录制了

**Comment by taojy123** [comment]
理论上不会的，你是不是录制的时候是不是光标还 focus 在 KeymouseGo 的软件中的 “停止” 按钮上
这时按下回车就相当于，点击了 “停止”

上面我猜测的，你可以把你的具体操作步骤说一下。

**Comment by PiPiNam** [comment]
我重新录制了一遍，发现问题依旧
1、打开软件，点击 “录制”，此时录制按钮变为 “结束”，周围有一圈蓝色框
2、我点击软件的其它空白处，“结束”周围的蓝色框消失
3、按下回车，直接就结束录制了

我猜测是在软件中接受读取时，当读取到 “Enter” 键就直接 return了，您可以调试再次确认一下。
（期待您的新版本！支持您！）

**Comment by taojy123** [comment]
好的 我再尝试重现一下。谢谢支持

**Comment by taojy123** [comment]
我试了一下，点击 “录制”，此时录制按钮变为 “结束”，周围有一圈蓝色框。
然后再点击软件的其它空白处，蓝色框不会消失，这时再按下 enter 就结束录制了。

你描述的情况是点击空白处后蓝框消失，我猜想即使这时候蓝框消失了，但 foucs 应该还在 “结束” 按钮上。
你可以试下，点击软件中的文本框或者软件外的任何其他地方，然后再按 enter。
