### ISSUE TITLE
后台模式能否让屏幕上的鼠标本身不移动？

### ISSUE THREAD

**Issue by Jetranger** [taojy123/KeymouseGo#3]
后台模式好像很有用

**Comment by taojy123** [comment]
后台模式就相当于在目标窗口中有一个“隐形的”鼠标在自动的操作，和屏幕上的你看见的鼠标互不影响的。
这个后台模式的坑太多了，所以我在最新的版本中干脆放弃了。
需要的话就使用老版本吧 https://github.com/taojy123/KeymouseGo/tree/v1.1

**Comment by Jetranger** [comment]
具体有些什么坑呢？
能简单介绍一下吗

**Comment by taojy123** [comment]
1、有时候无法准确获取目标窗体的句柄
2、只能模拟鼠标事件，没找到模拟键盘事件的方法
3、好像 MouseMove 事件也没法很好的模拟

**Comment by Jetranger** [comment]
哦，窗口句柄应该是API的问题吧，试用了一下，不能模拟鼠标滚轮的上滚和下滚，能否添加？

**Comment by taojy123** [comment]
你可以 fork 一下自己尝试完善下。
https://github.com/taojy123/KeymouseGo/blob/v1.1/Frame1.py 
210 行位置，是记录鼠标事件到脚本中，在这里要记录下滚轮事件
369 行往下是后台方式执行脚本中的事件的，这这里要模拟出滚轮事件。
你可以根据这个思路来做。

**Comment by Jetranger** [comment]
我从来没有用过Python，请问是用的哪个版本的Python

**Comment by taojy123** [comment]
Python 2.7，另外需安装第三方库 pywin32、wxPython、pyHook （https://github.com/taojy123/KeymouseGo/tree/master/libs）

如果有编程基础的话，花两天时间看一看 python 然后基本就可以改代码了。
这个项目就是我刚学 python 时的第一个练手项目，所以代码十分的简陋粗鄙 ☹️

**Comment by Jetranger** [comment]
感谢~感觉自己学的编程都还给老师了，已经十年没接触过编程了

**Comment by Jetranger** [comment]
折腾了半天，连编译环境都启动不了，我使用的是VSC+Python2.7 64bit+libs里面的所有包，通过pip将libs里的包安装完毕后，调试提示wx import错误

**Comment by Jetranger** [comment]
要搭建环境是不是必须安装32bit的Python，然后把所有libs里面的都安装一遍？或者请老师直接教一下怎么搭建环境和生成可以直接运行的exe

**Comment by taojy123** [comment]
32位 64位 都可以  我的libs里面也是分32和64的。安装对应的版本就行。
import wx 时报什么错。贴出来看下

**Comment by Jetranger** [comment]
能否用QQ联系，这样太不方便了

**Comment by taojy123** [comment]
67114208

**Comment by Jetranger** [comment]
加了，麻烦你通过一下
