### ISSUE TITLE
基于控件能否实现？

### ISSUE THREAD

**Issue by liuhao326** [taojy123/KeymouseGo#30]
有个想法，这个程序是基于坐标操作（类似于按键精灵）的，能否实现基于控件操作（类似于安卓端的Auto.js）？

基于坐标只能够重复固定的动作，但基于控件可以实现查找控件，然后对控件进行操作（如click），这使得实现功能更具灵活性，功能也更强大。

不知道Windows是否能够实现。

**Comment by taojy123** [comment]
很不错的想法。目前主要通过 pynput 只能实现根据坐标模拟。我回头研究一下是否有其他库能实现抓取控件的功能

**Comment by liuhao326** [comment]
> 很不错的想法。目前主要通过 pynput 只能实现根据坐标模拟。我回头研究一下是否有其他库能实现抓取控件的功能

Thanks

**Comment by hsysh** [comment]
@liuhao326 yinkaisheng的Python uiautomation库是基于控件是别的库，作者可以参考这个库

**Comment by taojy123** [comment]
考虑了一下如果做基于控件的，软件会变得十分复杂，失去了 “绿色、精简” 的特色，所以这个功能目前不做开发筹备了，谢谢您的支持。
