### ISSUE TITLE
希望能够实现鼠标拖动选择的功能

### ISSUE THREAD

**Issue by ITs-WHY** [taojy123/KeymouseGo#33]
在录制的时候发现按下鼠标左键拖动选择文本的过程无法被录制下载 
在日常使用中这个操作还是挺频繁的 希望能够解决

**Comment by ITs-WHY** [comment]
刚刚又尝试了通过按 shift + 上下左右 的方式来选择，也是不能选中那一块文本，但是再复制粘贴可以粘贴出本来应该选中的那一块文本

**Comment by taojy123** [comment]
好的，下个版本会改回 win32api 方式实现录制和模拟。回头加一个记录 mouse move 事件，这样就能模拟鼠标拖动轨迹了。
shift + 上下左右的问题已经建了另外的 issue，到时候会一并解决。

**Comment by taojy123** [comment]
v3.0 版本已发布，鼠标轨迹可被录制了
https://github.com/taojy123/KeymouseGo/releases/tag/v3.0
