### ISSUE TITLE
能否增加文字输入功能

### ISSUE THREAD

**Issue by cn-404-not-found** [taojy123/KeymouseGo#34]
有大量重复文字需要录入，目前我只能先复制，然后在软件中设置ctrl+V的组合键粘贴

**Comment by taojy123** [comment]
很好的建议，我会在下一个版本中增加这个功能，这个 issue 先不关，能这个功能做好了会在此 issue 下面回复你哈。

**Comment by taojy123** [comment]
v3.0 版本已发布，增加了文字输入的功能，语法为 `[100,  "EX", "input",  "你好 world"],` 具体可参看 readme 中的介绍。

https://github.com/taojy123/KeymouseGo/releases/tag/v3.0
