### ISSUE TITLE
读取配置

### ISSUE THREAD

**Issue by Alexkaer** [taojy123/KeymouseGo#35]
你好，能不能加个保存配置得功能， 改了快捷键和次数，每次启动都要重新改。 还有开机自启

**Comment by taojy123** [comment]
好的，下个版本考虑加进去。

**Comment by linwolfer** [comment]
> 好的，下个版本考虑加进去。

感谢作者的努力和负责！软件已日臻完善，不知道增加窗口识别（句柄）的功能，能否实现？ 😀

**Comment by taojy123** [comment]
@linwolfer  你好，你提到的 “窗口识别” 相当于在目标窗口中有一个“隐形的”鼠标在自动的操作，和屏幕上的你看见的鼠标互不影响的，这样吧？
这个功能其实很早以前做过，但是因为 bug 太多，不好维护，后来就删掉了。😂
具体可以看下这个 issue 的讨论 https://github.com/taojy123/KeymouseGo/issues/3

**Comment by linwolfer** [comment]
> @linwolfer 你好，你提到的 “窗口识别” 相当于在目标窗口中有一个“隐形的”鼠标在自动的操作，和屏幕上的你看见的鼠标互不影响的，这样吧？
> 这个功能其实很早以前做过，但是因为 bug 太多，不好维护，后来就删掉了。😂
> 具体可以看下这个 issue 的讨论 #3

对不起，语死早。
我想要的是窗口即使在后台未激活。但脚本运行的时候可以自动激活，或在窗口中自由切换。

**Comment by taojy123** [comment]
@linwolfer 大致了解了，加一个“激活窗口”的操作，现在用的 win32api，这个功能应该可以实现的。回头看下怎么做比较好。

**Comment by taojy123** [comment]
配置文件功能已在最新代码中合入
