### ISSUE TITLE
大神，能否提供个 linux版本

### ISSUE THREAD

**Issue by tzslg** [taojy123/KeymouseGo#36]

**Comment by taojy123** [comment]
2.x 版本是跨平台的
你可以下载或 clone 源代码 https://github.com/taojy123/KeymouseGo/releases/tag/v2.2
然后在 linux 上直接使用 python 运行
会在在 linux 上使用 pyinstaller 打包成单独的程序

**Comment by tzslg** [comment]
好的，谢谢
