### ISSUE TITLE
发现小bug

### ISSUE THREAD

**Issue by xingjiantian925** [taojy123/KeymouseGo#37]
首先感谢您的分享，以下为bug发生代码处
Frame1.py line 183 line184
self.choice_script.SetItems(self.scripts)
self.scripts = list(filter(lambda s: s.endswith('.txt'), self.scripts))
如此写法仍然将不以.txt结尾的文件显示到文本框中，导致作者调用filter的用意无法发挥作用

应将两句调换顺序

再次感谢您的分享

**Comment by taojy123** [comment]
谢谢你，现已修正 😊
