### ISSUE TITLE
中止运行和无坐标运行

### ISSUE THREAD

**Issue by linwolfer** [taojy123/KeymouseGo#39]
使用中发现两个“问题”：
1、直接通过软件界面运行脚本的话，可以用 F6 启动，F9 中止。但实际使用过程中，都是以命令行配合快捷键（其它软件）后台运行（非常酷，也非常爽）。可是脚本运行后，不知道如何中止……
2、脚本中，每一行的操作都带着坐标。不知道可不可以鼠标点击的动作，是跟随光标或焦点，就是光标移动到哪？或者焦点在哪个按钮或选择框？鼠标就在该处动作。
或者鼠标点击的动作，而不受坐标的限制？
最后实在感谢开发了如此实用、好用的软件。

**Comment by taojy123** [comment]
你好，谢谢支持。

1、现在通过命令行启动后，没有监听终止热键，只能通过 `Ctrl + C` 来结束运行。下个版本可以增加这个功能
**在命令行运行过程中监听 F9 终止热键**

2、这个功能使用 win32api 是可以实现的，就是单纯的模拟鼠标点击事件，可以考虑脚本中增加一种语法，类似这样： `[100,  "EM", "mouse left down",  [-1, -1]]`
**`[-1, -1]`用来表示在鼠标当前位置直接点击**。

**Comment by linwolfer** [comment]
测试了一下。[-1,-1]运行位置是最左上角，并非在当前位置或选中按钮。

**Comment by taojy123** [comment]
这个还没有开发哈，上面说的是我的预想

**Comment by linwolfer** [comment]
> 这个还没有开发哈，上面说的是我的预想

 😓是我太心急了。
谢谢你留心用户的需求。
期待新的版本、新的功能。
祝：身体安康、阖家欢乐。

**Comment by taojy123** [comment]
@linwolfer 
v3.1 版本已发布，上面提到的两个功能都已在最新版中添加。

详见：https://github.com/taojy123/KeymouseGo/releases/tag/v3.1

**Comment by linwolfer** [comment]
> @linwolfer
> v3.1 版本已发布，上面提到的两个功能都已在最新版中添加。
> 
> 详见：https://github.com/taojy123/KeymouseGo/releases/tag/v3.1

谢谢。辛苦了！！😀
