### ISSUE TITLE
UI界面问题

### ISSUE THREAD

**Issue by hn1sg** [taojy123/KeymouseGo#40]
2560×1440的UI显示不完整，可以修复一下
<img src = 'https://ftp.bmp.ovh/imgs/2020/10/c99fcfb0f29997f2.png' />

**Comment by taojy123** [comment]
应该是 win10 的屏幕缩放导致的，回头调一下

**Comment by taojy123** [comment]
你好能提供一下发生这个问题时的 屏幕缩放比例吗？

**Comment by hn1sg** [comment]
150

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: taojy123<mailto:notifications@github.com>
发送时间: 2020年12月18日 1:41
收件人: taojy123/KeymouseGo<mailto:KeymouseGo@noreply.github.com>
抄送: hn1sg<mailto:huadongwuyifan@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [taojy123/KeymouseGo] UI界面问题 (#40)


你好能提供一下发生这个问题时的 屏幕缩放比例吗？

―

**Comment by hn1sg** [comment]
可以考虑换个好看点的图标不😄

**Comment by taojy123** [comment]
这个 exe 换图标，网上有很多工具，可以自己换 😆

**Comment by hn1sg** [comment]
没找到几个工具啊，找过，要不你介绍下

**Comment by taojy123** [comment]
Resource Hacker
http://www.angusj.com/resourcehacker/

相关操作可以看下这篇
https://jingyan.baidu.com/article/e75057f203892febc91a8916.html
