### ISSUE TITLE
作者你好，我在使用该脚本的时候遇到了未录制上的问题

### ISSUE THREAD

**Issue by Db2k8652** [taojy123/KeymouseGo#44]
我的环境为 WIN10  1920*1080  125%缩放

目前使用脚本过程还是很开心 也非常感觉作者开发了一款这么精简而好用的“按键精灵”

在使用之前的版本没有遇到以下问题，这个问题是出现在V3.1版本

具体问题为：录制的过程中有时候会失效也就是说软件并没有在录制的过程中执行录制的功能
但如果我点击软件的窗口 会录制到操作 但是鼠标脱离窗口 窗口不在最前时 录制就失效了
这个也算是一个bug了
也希望作者可以修复一下

再次感谢作者的付出 谢谢。

**Comment by taojy123** [comment]
好的 谢谢！我先尝试重现一下问题。￼

**Comment by taojy123** [comment]
这个问题应该已在最新版本中修复
https://github.com/taojy123/KeymouseGo/releases/tag/v3.2
麻烦看下还会重新吗？
