### ISSUE TITLE
一些文档方面的小建议

### ISSUE THREAD

**Issue by intmian** [taojy123/KeymouseGo#46]
## 关于简介
作者您好，您在简介里写的

> simulate mouse clicks and keyboard input

此处的simulate英语里一般用于代指“模拟”，`simulate mouse clicks`这句直观的理解是“并非真的点击，而是在某个虚拟容器里模拟现实中软件的点击”。
也许换成auto或者之类的词或许会好些。
 `automate mouse clicks`或者`mouse click assistant`
## 关于`note.md`
也许和readme合并一起会更好些。因为一般使用者也许并不会详细查看源码文件夹里的md文件。
## 感谢您的付出

**Comment by taojy123** [comment]
谢谢，已修改为 `automate mouse clicks`

note.md 中主要是我之前给自己看的一些备忘，里面描述的问题可能随着 Python 版本的升级现在已经不复存在了。

**Comment by intmian** [comment]
嗯嗯好的，感谢您的付出
