### ISSUE TITLE
有没有办法获取句柄窗口 然后发送文本阿 。

### ISSUE THREAD

**Issue by huanx9** [taojy123/KeymouseGo#47]
有点好奇为什么后来把后台这个功能给砍了。

**Comment by huanx9** [comment]
如果可以获取窗口的话， 然后就可以把他变成一个文本发送器，但是这样的话 就要前台。。

**Comment by taojy123** [comment]
这个坑有点多，维护起来太困难了，我不太想把这个工具做的很复杂。因为如果有复杂需求的人更可能直接去下载功能强大的按键精灵。

**Comment by huanx9** [comment]
工具很好用，感谢。
 本来嘛，也不会编程， 如果能靠一些简单语句就可以实现一些奇奇怪怪的想法，还是蛮好的。  关闭了。

**Comment by taojy123** [comment]
谢谢支持😄
