### ISSUE TITLE
请问有直接启动某个txt script 的命令么

### ISSUE THREAD

**Issue by yaoing** [taojy123/KeymouseGo#5]
想在开机是做测试,代码里好像没看到命令行相关的代码额

**Comment by taojy123** [comment]
目前没有，这是个好需求，考虑新版本加入😄

**Comment by taojy123** [comment]
新版本已发布，增加了这个功能
https://github.com/taojy123/KeymouseGo/releases/tag/v1.4
使用方法：
> KeymouseGo.exe scripts/0314_1452.txt
或指定重复次数：
> KeymouseGo.exe scripts/0314_1452.txt 3

**Comment by yaoing** [comment]
这么快😮

**Comment by yaoing** [comment]
司机,开慢点..

**Comment by taojy123** [comment]
😂
