### ISSUE TITLE
能否增加启动录制和结束录制的快捷键？

### ISSUE THREAD

**Issue by cn-404-not-found** [taojy123/KeymouseGo#51]
没有快捷键，会录制不需要的内容，特别是在结束录制时候，我如果需要结束执行的时候将鼠标停留在特定位置，是无法实现的，因为此时需要将鼠标移动到结束录制处点击。。。。所以没法停在特定位置

**Comment by taojy123** [comment]
和这个问题类似
https://github.com/taojy123/KeymouseGo/issues/52

回头考虑增加快捷键，目前可以通过修改录制后脚本来解决。
