### ISSUE TITLE
建议增加结束录制快捷键

### ISSUE THREAD

**Issue by adairhu** [taojy123/KeymouseGo#52]
我在录制时，最后结束录制的按键动作也被一同录制下来了，在运行时它也会去操作一次结束按键

**Comment by adairhu** [comment]
抱歉，是我操作不正确，鼠标精度选为0即可解决

**Comment by taojy123** [comment]
嗯，现在会自动删除最后一个动作（即点击结束按钮的动作）
不过如果鼠标精度不为 0 的话，确实结束前的一段鼠标轨迹会被录下来。
暂时的处理办法是，手动将录制好的脚本的最后几行 mouse move 动作删去。

**Comment by adairhu** [comment]
好的，多谢指导。



发件人: taojy123<mailto:notifications@github.com>
发送时间: 2021年2月1日 16:17
收件人: taojy123/KeymouseGo<mailto:KeymouseGo@noreply.github.com>
抄送: Adair Hu<mailto:huminme@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [taojy123/KeymouseGo] 建议增加结束录制快捷键 (#52)


嗯，现在会自动删除最后一个动作（即点击结束按钮的动作）
不过如果鼠标精度不为 0 的话，确实结束前的一段鼠标轨迹会被录下来。
暂时的处理办法是，手动将录制好的脚本的最后几行 mouse move 动作删去。

―
