### ISSUE TITLE
有没有可能加一个不同分辨率下，坐标转换功能呢？

### ISSUE THREAD

**Issue by ygfly** [taojy123/KeymouseGo#53]
说实话调试一个能够稳定些运行的脚本并不容易，但调试好的脚本，想在另一个分辨率不同的电脑上运行目前是不能的，要是有一个不同分辨率下坐标转换功能，确实会方便不少。就是不知道实现的难度有多大。

**Comment by taojy123** [comment]
这是挺好的一个建议。
后面的版本考虑加入相对定位功能，比如：
`[50,   "EM", "mouse right down",   [50%, 50%]]`
表示在屏幕中心位置点下鼠标右键

我先把这个 feature 在这里记下了，回头开发。

**Comment by Monomux** [comment]
这个功能已在 #82 中加入。
