### ISSUE TITLE
特定的软件无法点击

### ISSUE THREAD

**Issue by duyunw** [taojy123/KeymouseGo#54]
当录制时遇到一些特定的软件无法执行。代码并不报错，也无异常，可继续执行。就是鼠标点击或者键盘按键效果无法展现，。可能是软件后台禁止了某些触发条件，防止进行录制点击等。无法点击效果多出现于游戏或者杀毒软件上，其中不同的系统效果可能还不一样，例如win7与win10的效果就有可能不一样。可以把键鼠点击效果更换为键鼠驱动试试，而是不用一些库或者系统I/O实现。

**Comment by taojy123** [comment]
好的，谢谢你的建议。
这种情形还需要有明确的重现步骤才方便定位。
游戏或杀毒软件可能有防外挂的机制，把这种模拟操作判定为了外挂行为。
