### ISSUE TITLE
同一个脚本，含中文输入，最新版直接报faild，3.0版可正常执行

### ISSUE THREAD

**Issue by cn-404-not-found** [taojy123/KeymouseGo#55]
删掉文字输入部分就正常，但是文字输入部分的语法是正确的
[中文输入报错.txt](https://github.com/taojy123/KeymouseGo/files/5999788/default.txt)

**Comment by taojy123** [comment]
之前注释中含有汉字会报错的问题已经修复，看你这个脚本是在 input 中的汉字，我再排查修复一下。
谢谢

**Comment by taojy123** [comment]
最新版本已修复

https://github.com/taojy123/KeymouseGo/releases/tag/v3.2.2
