### ISSUE TITLE
输入文字input命令不生效

### ISSUE THREAD

**Issue by NotNil1** [taojy123/KeymouseGo#56]
Frame1.py代码587行，引用了pyperclip里的方法，但是文件头没有引用pyperclip，是否这里报错了呢？
pyperclip.copy(text)

**Comment by taojy123** [comment]
谢谢，能不能帮忙修一下，建个PR。

**Comment by chenchenchenze** [comment]
同样等待该问题的修复中

**Comment by taojy123** [comment]
最新版本已修复

https://github.com/taojy123/KeymouseGo/releases/tag/v3.2.2
