### ISSUE TITLE
游戏场景录制的鼠标轨迹播放不正确

### ISSUE THREAD

**Issue by innc11** [taojy123/KeymouseGo#57]
我录制游戏(雨中冒险2，3d FPS游戏)内操作后再次播放时，鼠标滑动模拟有点问题，视角总是闪来闪去，没有那么平滑，即使是把轨迹精度改为1也是如此

我猜可能是因为游戏锁定了鼠标导致的，请问这个问题有解决的可能性吗，谢啦

**Comment by taojy123** [comment]
在游戏中使用时，有被认定为外挂的可能性，所以导致程序失效或偏差。

这个 issue 应该也是类似问题 https://github.com/taojy123/KeymouseGo/issues/54

**Comment by innc11** [comment]
谢啦，我猜要模拟游戏的话还得从驱动层进行模拟，或者是有防作弊机制，不管怎样还是谢谢啦
