### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by controlloli** [taojy123/KeymouseGo#59]
1.期待支持快捷键启动和停止录制
2.对游戏没办法输入

**Comment by taojy123** [comment]
游戏支持比较困难，会被认为是外挂。

**Comment by neurbio** [comment]
可否加入执行提示音，方便确认延时任务已启动。

**Comment by taojy123** [comment]
> 可否加入执行提示音，方便确认延时任务已启动。

谢谢  很好的建议

**Comment by taojy123** [comment]
> 可否加入执行提示音，方便确认延时任务已启动。

已在 https://github.com/taojy123/KeymouseGo/pull/79 中增加
