### ISSUE TITLE
请问运行后怎么自动关闭软件？

### ISSUE THREAD

**Issue by tt3736035** [taojy123/KeymouseGo#6]
这功能很实用啊，为什么没有？

**Comment by taojy123** [comment]
窗口模式下，默认是F12终止运行。
命令行模式下，直接 ctrl-c 中断退出就行了。

**Comment by tt3736035** [comment]
窗口模式，我就是想不用再按键，运行完脚本自己自动退出，能在脚本最后加个结束进程之类的吗

**Comment by taojy123** [comment]
在软件窗口中点击“开始”，然后运行结束后直接把整个窗口退了，我觉得这个不太合理啊。
如果你个人有这方面的需求的话，可以 fork 一下自己修改一下源代码。
思路是，在 Frame1.py 491 行处加上 mself.Destroy() 应该就差不多了。
