### ISSUE TITLE
功能建议 可否使Input内容依序变化

### ISSUE THREAD

**Issue by Seven-pence** [taojy123/KeymouseGo#60]
比如第一次输入1第二次输入2之类的

**Comment by ygfly** [comment]
Input功能感觉使用的是Windows的ctrl-v功能，有一定的局限性，比如win下用虚拟机安装的Android，在这个Android下，只会input一个字符v   。

**Comment by taojy123** [comment]
确实是这样的，目前这个程序就是面向一些比较简单的场景，专业化复杂场景可能还是需要一些成熟的商业软件来支持，比如按键精灵
