### ISSUE TITLE
+1 应该加入一个定时执行功能，比如每天08:00执行一次

### ISSUE THREAD

**Issue by Ponegoat** [taojy123/KeymouseGo#63]
+1 应该加入一个定时执行功能，比如每天08:00执行一次

_Originally posted by @501miles in https://github.com/taojy123/KeymouseGo/issues/58#issuecomment-816384101_

**Comment by taojy123** [comment]
恩，在考虑新的脚本语法，来支持定时动作

**Comment by a9876112** [comment]
可以用Windows的计划管理器实现。@Ponegoat

**Comment by ZLake** [comment]
直接python包一个定时调度就行了吧
