### ISSUE TITLE
能否增加倍速播放和执行时的「暂停键」

### ISSUE THREAD

**Issue by Ponegoat** [taojy123/KeymouseGo#64]
软件很喜欢很好用

1.能否增加一个播放的时候倍速选项让手动慢速录制的脚本执行的快一点！

2.还有一个功能是：在执行脚本的时候能否直接按[暂停键]暂停播放等我处理了一下有些不同的细节后再按[暂停键]开始继续执行，因为我们录制的脚本很多时候不能很好的适应复杂的文本处理的要求有些可能需要临时修改一下窗口的细节手动调整后在按暂停键继续播放脚本呢！

**Comment by taojy123** [comment]
感谢提议，最近工作有点忙，回头有时间了会整理近期大家提出的功能建议放到下个版本中。
也希望有能力的朋友可以帮忙开发，给我提PR

**Comment by Going2333** [comment]
> 感谢提议，最近工作有点忙，回头有时间了会整理近期大家提出的功能建议放到下个版本中。
> 也希望有能力的朋友可以帮忙开发，给我提PR

期待作者更新。
这个工具很好用，单位的电脑系统32位的，但是又不想用1.5老版本，研究了几天pyinstaller打包最新版3.2.2终于成功了。

我的电脑win10 64位，装的python3.7 32位，pyinstaller 4.3，
pywin32和pyperclip直接用pip装的：
`pip install pywin32==228
pip install pyperclip==1.8.0`
另外，有朋友说pynput有报错，可能是版本太高，所以装的1.6.8
`pip install pynput==1.6.8`
wxPython装的4.0.5的：
`pip install "https://files.pythonhosted.org/packages/f0/33/0465fa0a9f34de588d3355d0de4685c6686f5e25234b4a974eaa20c35139/wxPython-4.0.5-cp37-cp37m-win32.whl"`
至于pywinhook装的1.6.2的：
`pip install "https://download.lfd.uci.edu/pythonlibs/q4trcu4l/pyWinhook-1.6.2-cp37-cp37m-win32.whl"`
最后就用pyinstaller或者基于pyinstaller的auto-py-to-exe（有图形化界面操作，还阔以）打包：
`pyinstaller -F -w KeymouseGo.py`
 记录一下，仅供跟我一样有32位需求，但是不懂python的萌新参考。

**Comment by Monomux** [comment]
Added features in PR #76

**Comment by taojy123** [comment]
@Monomux  感谢支持！
