### ISSUE TITLE
能否考虑增加ubuntu版本

### ISSUE THREAD

**Issue by YangDunYu** [taojy123/KeymouseGo#65]
有些任务需要持续执行，不想使用windows占用太多资源，能否编译成ubuntu图形界面版本，方便性能较差的本地机器或者远程部署使用

**Comment by taojy123** [comment]
老版本使用 pynput 来实现模拟点击的，因为太难维护在 3.0 版本开始放弃了。
如果感兴趣，可以参考老版本的代码 https://github.com/taojy123/KeymouseGo/releases/tag/v2.2
