### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by hyyw2020** [taojy123/KeymouseGo#66]
增加开始录制的热键，结束录制的热键。增加自定义热键。热键冲突显示。随机鼠标轨迹（起始与过程中随机，但最终点击到设定位置。）点击一次N个某按钮或某动作后默认为M次连续循环。动作间隔可设置为毫秒/秒。额外提供除了中文之外的语言包供下载如英语。生成TXT是否已经支持另存为？以及TXT更改后重新导入？在使用中并没有看见这些重要功能。 @taojy123

**Comment by taojy123** [comment]
感谢，挺多挺好的建议

**Comment by taojy123** [comment]
开始/终止 录制和执行 的快捷键均已再最新版本中实现
