### ISSUE TITLE
自动化按键只在文本输入时管用，玩游戏控制按键时不管用

### ISSUE THREAD

**Issue by JianyueZ** [taojy123/KeymouseGo#67]
感谢大佬！遇到问题了求助！
我想用来玩游戏时精确控制按键之间的时间间隔。脚本是这样的：
[
 [0,"EK","key down",[69,"E",0]],
 [200,"EK","key up",[69,"E",0]],
 [5000,"EK","key down",[83,"S",0]],
 [200,"EK","key up",[83,"S",0]]
]

结果玩游戏时没反应，而同一个游戏里如果打开文字聊天框，却能够自动输入脚本设置的按键。这是咋回事？怎么调整呀？

我之前试了AutoHotkey也是这样只能写文本不能控制游戏按键，而按键精灵和TinyTask则完全管用。

**Comment by taojy123** [comment]
因为游戏一般会有一些反外挂的机制。按键精灵针对此会做一些特殊的优化。
本工具无法用来做游戏辅助的。

**Comment by taojy123** [comment]
还是很感谢你的支持和使用，希望在其他领域有所帮助

**Comment by JianyueZ** [comment]
> 因为游戏一般会有一些反外挂的机制。按键精灵针对此会做一些特殊的优化。
> 本工具无法用来做游戏辅助的。

懂了。感谢！
