### ISSUE TITLE
建议“录制”按钮可是设置快捷键，否则会录制前后开始和结束的无用轨迹

### ISSUE THREAD

**Issue by calonye** [taojy123/KeymouseGo#68]
如题

**Comment by taojy123** [comment]
好的，考虑增加快捷键

**Comment by 1441916133** [comment]
我昨天使用的时候也发现了无用轨迹比较多，今天参考文档对生成的txt文本进行修改。删除最后一次点击后的move mouse动作，偶尔会出现最后一步的点击失效，不知道是什么问题。同样的文本有些正常，有些不正常，只要第一次运行正常，往后就是正常的。不知道是不是玄学。
win10 家庭版 20H2 R5-4600平台
