### ISSUE TITLE
能否检测特定位置弹出的选项，如“确定”按钮，如果检测到就点击，检测不到就忽略。

### ISSUE THREAD

**Issue by ghost** [taojy123/KeymouseGo#71]
现在好的网上课程会弹出这类东西，检测学员是否真的在看，现在只能强行在特定位置定时点击一下，如果这时有弹出特定按钮，点击后就继续播放；如果没有，就暂停播放，导致多费了一倍的学习时间。如果不同位置有弹出按钮的话，要设置多个定时点击，这导致需要几倍的学习时间，效率太低了。不知道能否在第一次弹出按钮时，抓取一个按钮的图片，然后定时和特定位置比对，匹配上就点击。纯自己瞎想，不知道是否可行。或者谁知道有类似功能的软件，推荐一下。

**Comment by taojy123** [comment]
一般游戏或学习软件都有反外挂机制，所以即使 keymousego 开发了这个功能，可能也没法实际发挥作用 😒
