### ISSUE TITLE
增添新功能

### ISSUE THREAD

**Issue by whalefallll** [taojy123/KeymouseGo#75]
能否增添2个功能:

1. 修改脚本名称.这样就不用找文件修改名称了  比较方便
2. 添加一个编辑入口  也是省去找文件的麻烦

**Comment by ygfly** [comment]
修改脚本名称 只要用windows的重命名功能就能实现吧。

**Comment by taojy123** [comment]
目前直接修改文件名其实挺方便的，就不费力气做到软件界面中了哈
