### ISSUE TITLE
建议增加某段指令重复n次功能。

### ISSUE THREAD

**Issue by ygfly** [taojy123/KeymouseGo#78]
现在只有全部指令循环执行n次的功能，而部分指令循环执行的功能好像没有。

**Comment by taojy123** [comment]
这需要脚本中支持部分循环语法，这个工具以简单应用为主，所以短期内不考虑增加这个功能哈。

**Comment by ygfly** [comment]
如果太麻烦就算了，现在功能基本满足了我的需要。把要循环的指令段复制n遍，也能变相解决循环的问题哈。

**Comment by taojy123** [comment]
嗯嗯，目前就在脚本文件中多复制几遍，简单粗暴好方便😄
