### ISSUE TITLE
录制脚本后鼠标会位移

### ISSUE THREAD

**Issue by aiastia** [taojy123/KeymouseGo#8]
举个例子 ，录制的时候  excel  鼠标a1 移动到 a2 ，a3 . a4
 然后 录制结束。点击启动鼠标会移动到下面三行左右位置。

**Comment by taojy123** [comment]
我好像没法重新你说的问题，方便录制一个视频演示一下吗？

**Comment by aiastia** [comment]
录制的时候 软件没有显示出来。
[新建 Microsoft Excel 工作表.xlsx - Excel 2019-04-09 18-54-36.zip](https://github.com/taojy123/KeymouseGo/files/3058533/Microsoft.Excel.xlsx.-.Excel.2019-04-09.18-54-36.zip)
[0409_1855.txt](https://github.com/taojy123/KeymouseGo/files/3058535/0409_1855.txt)

**Comment by taojy123** [comment]
哈哈，没有看懂你的视频

**Comment by aiastia** [comment]
前面一段是录制的 ，后面一段是启动的。用xbox 的哪个 录制功能 ……

**Comment by aiastia** [comment]
[bandicam 2019-04-12 15-49-53-056.zip](https://github.com/taojy123/KeymouseGo/files/3072166/bandicam.2019-04-12.15-49-53-056.zip)
[0412_1550.txt](https://github.com/taojy123/KeymouseGo/files/3072167/0412_1550.txt)

**Comment by aiastia** [comment]
换个软件录制一下，你看看。 鼠标移动的位置感觉不对……启动是按f8 启动。怕鼠标初始位置 有影响

**Comment by taojy123** [comment]
再仔细看了下视频
第6秒到36秒是录制脚本
第36秒到结束是运行脚本
是这样吗？

**Comment by taojy123** [comment]
我看了你发的脚本好像和视频的内容不是对应的。建议你将软件窗口也一起录制到视频中，这样我可以知道，你具体做了什么操作。期望的结果是什么，实际的结果是什么

**Comment by taojy123** [comment]
第二次的录像看清楚了，很能说明问题了。
像是录制的bug，也就是说录制的时候的鼠标真实坐标与被记录下来的坐标不一致。
我系统上暂时没法重现出来，我想一想，可能是什么原因会导致再个别系统上出现这个问题。

**Comment by taojy123** [comment]
我大概知道原因了，你的屏幕应该是比较高分辨率的，在显示设置里可能设置了 125% 或 150% 大小显示。
这导致了，录制记录的点坐标与实际操作的点坐标产生了 125% 或 150% 的漂移。
我会在下一个版本中针对这种问题修复一下。

**Comment by aiastia** [comment]
是的…… 现在  125%的  大概什么时候出下一个版本。现在临时解决方案是  调100%吗……（尴尬

**Comment by taojy123** [comment]
如果是我上面分析的这样，那只能先调100%了 🤐

**Comment by aiastia** [comment]
![image](https://user-images.githubusercontent.com/19776350/56030204-de4e0c80-5d4e-11e9-83c0-adc58ee27f0a.png)
调到100% 可以了 但是出现了这个错误

**Comment by taojy123** [comment]
这个是在执行脚本的过程中报出的，还是一打开软件就弹出

**Comment by aiastia** [comment]
刚才 录制 之后  试了一下，感觉是分辨率问题  ，关闭的时候。 之前也有 ，都是录制完  退出软件的时候。单是不是每次都发生。

**Comment by aiastia** [comment]
![image](https://user-images.githubusercontent.com/19776350/56038786-56273180-5d65-11e9-82c5-15c67cc742a2.png)
突然 发现 GitHub 没显示这短话但是 给我推送邮箱了 （

**Comment by taojy123** [comment]
那条留言是我看错了视频，后来删了，请忽略。
报错 R6031 的问题，我查了一下，发现 word 也有人遇到类似的问题
https://jingyan.baidu.com/article/e73e26c0ad987924adb6a7ad.html
所以可能是系统方面的 bug。
顺便说一下，这个程序是我很早以前刚学 python 时写的，有点简陋。最近打算重写一遍，应该会优化不少问题。

**Comment by aiastia** [comment]
不是打不开，就是录制的运行 ，在退出的时候遇到的 。
另外 新版本 大概什么时候发布？

**Comment by taojy123** [comment]
可能下个月😄

**Comment by taojy123** [comment]
修复版本已发布
https://github.com/taojy123/KeymouseGo/releases/tag/v1.5
可以下载测试下是否有效

**Comment by aiastia** [comment]
感谢 。可以 在  125% 的时候运行了 。150%还没试。不过 录制 运行后 。在关闭的时候又出现了那个提示 。

**Comment by taojy123** [comment]
那个提示如果不会影响正常操作，就先忽略了吧，暂时没有找到好的解决办法

**Comment by langeyouxiang** [comment]
当时做wpf项目时遇到过windows改变zoom会影响dpi.給你个参考案列.      
120dpi就是windows设置了125%zoom,你获取屏幕的高宽要乘以scaling.          
switch (dpi)
                {
                    case 120:
                        scaling = 1.25F;
                        break;
                    case 144:
                        scaling = 1.50F;
                        break;
                    case 168:
                        scaling = 1.75F;
                        break;
                    case 192:
                        scaling = 2.00F;
                        break;
                    case 216:
                        scaling = 2.25F;
                        break;
                    case 240:
                        scaling = 2.50F;
                        break;
                    case 264:
                        scaling = 2.75F;
                        break;
                    case 288:
                        scaling = 3.00F;
                        break;
                    default:
                        scaling = 1.00F;
                        break;
                }

**Comment by taojy123** [comment]
@langeyouxiang  感谢。
这个问题，我给 pynput 提过 issue，就是这个: https://github.com/moses-palmer/pynput/issues/153
目前应该也没有特别好的解决方案，这个 issue 里有人提出过一个解决方案 https://github.com/moses-palmer/pynput/issues/153#issuecomment-545087338
我试了以后确实有效果，但是有一些副作用，所以目前 KeymouseGo 针对屏幕缩放的解决方案还是手动填百分比。

**Comment by Poachedegg** [comment]
...你好，遇到相同的问题，但是即使是调到100%测试，当天正常， 次日的话依旧出现偏移现象，有可能重启后会自动便宜？

**Comment by taojy123** [comment]
@Poachedegg 
你遇到的问题和上面这个还不太一样，如果坐标偏移的话，第1次就会偏移的。
方便提供一个可以重现你说描述的问题的，最小规模的脚本吗？
