### ISSUE TITLE
录制过程中按F9不会终止

### ISSUE THREAD

**Issue by JOE-525** [taojy123/KeymouseGo#81]
不知道是不是我自己的电脑对按键冲突了还是啥, 按f9会被记录下来
![Snipaste_2022-01-21_16-04-34](https://user-images.githubusercontent.com/54732130/150489604-1d4ec288-d971-4653-b933-e9d933f4d9ea.png)

**Comment by JOE-525** [comment]
自己好像是理解错了, 好像热键是用来开启/终止脚本的运行的, 不是用来录制的.
* 我觉得可以加一个录制终止的热键, 这样可以减少一些不必要的移动鼠标的操作

**Comment by taojy123** [comment]
嗯，可以考虑，“结束录制”快捷键

**Comment by JOE-525** [comment]
嗯嗯, 我下次提pr的时候可能会自己尝试弄一下吧
