### ISSUE TITLE
高DPI界面文字换行重叠

### ISSUE THREAD

**Issue by LinJinKang** [taojy123/KeymouseGo#83]
![image](https://user-images.githubusercontent.com/54579927/150677204-f8517bc6-f764-473c-87e8-ccf020df1747.png)

# 开启高DPI缩放替代后文字换行重叠了

![image](https://user-images.githubusercontent.com/54579927/150677144-56c34578-8c3e-4168-8866-c40ed3554b6d.png)

**Comment by taojy123** [comment]
是的，之前也发现了这个问题。还没想到好的解决办法

**Comment by Monomux** [comment]
可以通过SetProcessDpiAwareness让程序适配系统DPI，同时所有控件大小与位置用wxWidget的device-independent pixels设置以适应不同DPI
Attempt to fix in PR #85

**Comment by taojy123** [comment]
@Monomux  已合入，谢谢！
