### ISSUE TITLE
录制的时候，切换到其他程序，不能记录操作

### ISSUE THREAD

**Issue by Ghost-GG** [taojy123/KeymouseGo#87]
录制的时候，切换到其他应用程序，不记录操作。在桌面可以记录操作。

**Comment by taojy123** [comment]
这个问题，好像没法重现

**Comment by NanachiHub** [comment]
很容易重现，玩黑魂的时候想录制脚本自己打，进去后键盘的移动操作不会被记录，但是切换界面操作有反应

**Comment by taojy123** [comment]
我知道了，一般游戏里面都有反外挂的机制。
KeymouseGo 没有针对游戏做适配和优化。
