### ISSUE TITLE
记得看到过编译好的KeymouseGo v3.2.2  32位版。

### ISSUE THREAD

**Issue by ygfly** [taojy123/KeymouseGo#88]
记得看到过编译好的KeymouseGo v3.2.2  32位版，应该是在这里吧，但却找不到了，哪位好心人知道把链接发一下。

**Comment by ygfly** [comment]
清晰的记得还有编译 的注意事项，咋就找不到了呢？

**Comment by taojy123** [comment]
https://github.com/taojy123/KeymouseGo/releases/tag/v1.5

只有老版本支持32位，可以在这里找到

**Comment by taojy123** [comment]
https://github.com/taojy123/KeymouseGo/blob/master/note.md

是这个吗？

**Comment by ygfly** [comment]
[KeymouseGo_v3.2.2_x86.zip](https://github.com/taojy123/KeymouseGo/files/8052308/KeymouseGo_v3.2.2_x86.zip)
在我的网盘找到了，不是我编译的，原来下载的地方咋也找不到了。

**Comment by taojy123** [comment]
帮你“挖坟”挖出来了😄
https://github.com/taojy123/KeymouseGo/issues/64
@ygfly
