### ISSUE TITLE
请问能暂停脚本么？

### ISSUE THREAD

**Issue by Kugia** [taojy123/KeymouseGo#9]

**Comment by taojy123** [comment]
这个功能目前没有设计呢😂

**Comment by Kugia** [comment]
加暂停需要改哪里呀  有点好奇😃

**Comment by taojy123** [comment]
先加一个类似启动或停止的快捷键，按下后标记系统状态为 `暂停中`
`Frame1.py` 的 `RunScriptClass` 中有个循环 `for i in range(0, steps)` 这里面是依次执行脚本的每一步
可以在这下面加一段逻辑如果系统为 `暂停中` ，就在这里 sleep 几秒钟，然后再判断系统状态，直到系统不是 `暂停中` 了就往下继续执行。
实现方案有很多，上面只是一种思路。😄

**Comment by fisherwise** [comment]
感觉这个功能挺有用的...大佬最近有计划加吗？
没有的话我可以建个pr

**Comment by taojy123** [comment]
@fisherwise  欢迎的!
最近确实比较忙，没有时间开发这个 feature。
期待你贡献代码哈😁

**Comment by fisherwise** [comment]
PR #16
