### ISSUE TITLE
win11 ARM not working

### ISSUE THREAD

**Issue by xdagx** [taojy123/KeymouseGo#90]
最新源代码编译，win11 ARM 平台上不能正常工作，可以录制，但启动后，坐标混乱。
老版本3.2.2可以正常使用。

**Comment by taojy123** [comment]
麻烦 @Monomux 看下，是不是 https://github.com/taojy123/KeymouseGo/pull/85 这里改动有影响

**Comment by xdagx** [comment]
不是界面UI混乱，应该是相对坐标的问题吧，老版本用的绝对坐标就没问题。
