### ISSUE TITLE
3.2.2版本无法记录无线鼠标滚轮滚动

### ISSUE THREAD

**Issue by LingLing1301** [taojy123/KeymouseGo#92]
我尝试记录鼠标滚轮滚动，但是没有效果，我使用ROG 斯巴达X鼠标，在无线模式下无法记录鼠标滚轮滚动.

**Comment by Monomux** [comment]
3.2.2的版本并不支持记录鼠标滚轮，你可以下载最新的代码编译使用。

**Comment by Monomux** [comment]
我并没有看到主页有新版本的release，就擅自打包了下最新的程序:
[KeymouseGo_x86.zip](https://github.com/taojy123/KeymouseGo/files/8086191/KeymouseGo_x86.zip)
[KeymouseGo_x86-64.zip](https://github.com/taojy123/KeymouseGo/files/8086192/KeymouseGo_x86-64.zip)
