### ISSUE TITLE
快捷键

### ISSUE THREAD

**Issue by LingLing1301** [taojy123/KeymouseGo#94]
添加一个录制的快捷键或许是个好主意，因为在点击录制后，通常需要关闭KeymouseGo的界面，会点击窗口右上角的隐藏，但KeymouseGo会记录这个操作，每次录制完脚本后如果不手动修改脚本，KeymouseGo就会先按照录制的那样执行点击操作，这样很不方便。
当然，这只是个人想法，看上去我的问题有点多，如果不想采纳或者不能采纳这个提议，可以无视这个问题。

**Comment by taojy123** [comment]
挺好的建议！

现在只有开始运行和结束运行的快捷键

考虑增加开始录制和结束录制的快捷键

谢谢

**Comment by taojy123** [comment]
https://github.com/taojy123/KeymouseGo/issues/66

这里也提到了  回头统一处理一下
