### ISSUE TITLE
快捷键无法启动与其他

### ISSUE THREAD

**Issue by wongqing1688** [taojy123/KeymouseGo#97]
发现1，当运行一次后，鼠标停留在其他任务窗口界面，不在桌面时，脚本无法触发动作。
2，可否添加一个定时执行启动的功能，比如24小时一次
3，当屏幕锁屏时，脚本无法工作，这个可能是WINDOWS的限制，我不熟悉WIN机制

**Comment by taojy123** [comment]
1、可能正在运行的某些程序有“反作弊”功能，导致 KeymouseGo 无法正常工作，比如一般在游戏中是无法使用的。
2、目前有个变通的方法可以在脚本中手动添加超长时间的延时，然后把脚本核心内容复制几遍。
3、锁屏时确实是无法工作的
