### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by halfswing** [taojy123/KeymouseGo#99]
有没有可能增加找图功能？那样就更棒了

**Comment by littlemengnew** [comment]
有没有后台功能啊，Windows多桌面让他在一个桌面操作也行最好是与应用一起最小化都行

**Comment by ChengYan-3721** [comment]
请问能不能加一个启动录制和停止录制的全局热键啊？要用鼠标点录制和结束会影响录制的轨迹

**Comment by ChengYan-3721** [comment]
> 请问能不能加一个启动录制和停止录制的全局热键啊？要用鼠标点录制和结束会影响录制的轨迹

我已经解决了，录制好后把前后多余的轨迹删除就可以了，非常好用的小工具！

**Comment by taojy123** [comment]
> 

https://github.com/taojy123/KeymouseGo/issues/102 这里也提到了，目前可能没有这方面功能开发的打算
